// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'app_error.dart';
import 'db.dart';
import 'event_bus.dart';
import 'frb_generated.dart';
import 'lnurl_client.dart';
import 'multimint.dart';
import 'nostr.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'lib.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `create_event_bus`, `create_nostr_client`, `error_to_flutter`, `get_database`, `get_db`, `get_multimint`, `get_nostr_client`, `get_pin_manager`, `get_recovery_relays`, `info_to_flutter`, `nwc_limit_msats`, `parse_ecash`, `payment_error_to_flutter`, `verify_current_pin`, `write_nwc_limits`
// These functions are ignored because they have generic arguments: `balance`, `federations`, `get_invoice_network`, `log_error`, `parse_ecash`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MultimintParseContext`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`

Future<EventBusMultimintEvent> getEventBus() =>
    RustLib.instance.api.crateGetEventBus();

Future<void> addRecoveryRelay({required String relay}) =>
    RustLib.instance.api.crateAddRecoveryRelay(relay: relay);

Future<void> createNewMultimint({
  required String path,
  required bool isDesktop,
}) => RustLib.instance.api.crateCreateNewMultimint(
  path: path,
  isDesktop: isDesktop,
);

Future<void> loadMultimint({required String path, required bool isDesktop}) =>
    RustLib.instance.api.crateLoadMultimint(path: path, isDesktop: isDesktop);

Future<void> createMultimintFromWords({
  required String path,
  required List<String> words,
  required bool isDesktop,
}) => RustLib.instance.api.crateCreateMultimintFromWords(
  path: path,
  words: words,
  isDesktop: isDesktop,
);

Future<List<String>> getMnemonic() => RustLib.instance.api.crateGetMnemonic();

Future<FederationSelector> joinFederation({
  required String inviteCode,
  required bool recover,
}) => RustLib.instance.api.crateJoinFederation(
  inviteCode: inviteCode,
  recover: recover,
);

Future<void> backupInviteCodes() =>
    RustLib.instance.api.crateBackupInviteCodes();

Future<void> rejoinFromBackupInvites() =>
    RustLib.instance.api.crateRejoinFromBackupInvites();

Future<List<(FederationSelector, bool)>> federations() =>
    RustLib.instance.api.crateFederations();

Future<void> refreshConnections() =>
    RustLib.instance.api.crateRefreshConnections();

Future<BigInt> balance({required FederationId federationId}) =>
    RustLib.instance.api.crateBalance(federationId: federationId);

/// Largest amount (in msats) the user can pay to `lnaddress_or_lnurl` out of
/// this federation's balance through `gateway`, including that gateway's
/// routing fee and the federation fee. `is_lnv2` selects the module to quote
/// against, so this matches the gateway the user picked on the number pad.
/// Backs the "Max" button when paying a Lightning Address / LNURL. Errors if
/// the balance is too low to send any amount after fees.
///
/// The routing fee depends on whether the payment needs a Lightning hop at all,
/// which is a property of the *invoice* — and the amount has to be chosen
/// before the real invoice can be requested. So this first fetches a throwaway
/// invoice at the recipient's `minSendable`, purely to read who the payee is,
/// and quotes against the fee schedule that answer implies. Without the probe
/// the quote would have to assume the expensive Lightning-swap fee and would
/// silently strand the difference whenever the recipient is on this federation.
///
/// The probe invoice is never paid; it simply expires. `parse` already does the
/// same thing to learn an address's network, so this is the second such
/// throwaway on the path, not the first.
///
/// The result is also clamped to the recipient's `maxSendable` — offering a
/// "max" the destination would reject is worse than offering a smaller one.
Future<BigInt> maxLightningSend({
  required FederationId federationId,
  required String lnaddressOrLnurl,
  required String gateway,
  required bool isLnv2,
}) => RustLib.instance.api.crateMaxLightningSend(
  federationId: federationId,
  lnaddressOrLnurl: lnaddressOrLnurl,
  gateway: gateway,
  isLnv2: isLnv2,
);

Future<(String, OperationId, String, String, BigInt)> receive({
  required FederationId federationId,
  required BigInt amountMsatsWithFees,
  required BigInt amountMsatsWithoutFees,
  required BigInt federationFeeMsats,
  required BigInt gatewayFeeMsats,
  required String gateway,
  required bool isLnv2,
}) => RustLib.instance.api.crateReceive(
  federationId: federationId,
  amountMsatsWithFees: amountMsatsWithFees,
  amountMsatsWithoutFees: amountMsatsWithoutFees,
  federationFeeMsats: federationFeeMsats,
  gatewayFeeMsats: gatewayFeeMsats,
  gateway: gateway,
  isLnv2: isLnv2,
);

Future<ReceiveAmount> computeReceiveAmountWithFees({
  required FederationId federationId,
  required String gatewayUrl,
  required bool isLnv2,
  required BigInt amountMsats,
  required bool includeFees,
}) => RustLib.instance.api.crateComputeReceiveAmountWithFees(
  federationId: federationId,
  gatewayUrl: gatewayUrl,
  isLnv2: isLnv2,
  amountMsats: amountMsats,
  includeFees: includeFees,
);

Future<String> getInvoiceFromLnaddressOrLnurl({
  required FederationId federationId,
  required BigInt amountMsats,
  required String lnaddressOrLnurl,
}) => RustLib.instance.api.crateGetInvoiceFromLnaddressOrLnurl(
  federationId: federationId,
  amountMsats: amountMsats,
  lnaddressOrLnurl: lnaddressOrLnurl,
);

/// Fetch withdraw parameters from a LNURLw endpoint — see
/// [`lnurl_client::fetch_withdraw_params`]. Pure read, no side effects: call it
/// first so the UI can confirm the withdraw with the user before money moves.
Future<LnurlWithdrawParams> fetchLnurlWithdraw({required String url}) =>
    RustLib.instance.api.crateFetchLnurlWithdraw(url: url);

/// Create a Lightning invoice, send it to the LNURLw callback URL, and return
/// the operation ID. The caller should then use `await_receive` to wait for
/// the external service (e.g. Boltcard) to pay the invoice.
Future<OperationId> executeLnurlWithdraw({
  required FederationId federationId,
  required String callback,
  required String k1,
  required BigInt amountMsatsWithoutFees,
  required BigInt amountMsatsWithFees,
  required BigInt federationFeeMsats,
  required BigInt gatewayFeeMsats,
  required String gatewayUrl,
  required bool isLnv2,
}) => RustLib.instance.api.crateExecuteLnurlWithdraw(
  federationId: federationId,
  callback: callback,
  k1: k1,
  amountMsatsWithoutFees: amountMsatsWithoutFees,
  amountMsatsWithFees: amountMsatsWithFees,
  federationFeeMsats: federationFeeMsats,
  gatewayFeeMsats: gatewayFeeMsats,
  gatewayUrl: gatewayUrl,
  isLnv2: isLnv2,
);

Future<OperationId> send({
  required FederationId federationId,
  required String invoice,
  required String gateway,
  required bool isLnv2,
  required BigInt amountWithFees,
  required BigInt federationFeeMsats,
  required BigInt gatewayFeeMsats,
  String? lnAddress,
}) => RustLib.instance.api.crateSend(
  federationId: federationId,
  invoice: invoice,
  gateway: gateway,
  isLnv2: isLnv2,
  amountWithFees: amountWithFees,
  federationFeeMsats: federationFeeMsats,
  gatewayFeeMsats: gatewayFeeMsats,
  lnAddress: lnAddress,
);

Future<LightningSendOutcome> awaitSend({
  required FederationId federationId,
  required OperationId operationId,
}) => RustLib.instance.api.crateAwaitSend(
  federationId: federationId,
  operationId: operationId,
);

Future<(FinalReceiveOperationState, BigInt)> awaitReceive({
  required FederationId federationId,
  required OperationId operationId,
}) => RustLib.instance.api.crateAwaitReceive(
  federationId: federationId,
  operationId: operationId,
);

Future<List<PublicFederation>> listFederationsFromNostr({
  required bool forceUpdate,
}) => RustLib.instance.api.crateListFederationsFromNostr(
  forceUpdate: forceUpdate,
);

Future<PaymentPreviewWithGateways> paymentPreviewWithGateways({
  required FederationId federationId,
  required String bolt11,
}) => RustLib.instance.api.cratePaymentPreviewWithGateways(
  federationId: federationId,
  bolt11: bolt11,
);

Future<FederationMeta> getFederationMeta({
  String? inviteCode,
  FederationId? federationId,
}) => RustLib.instance.api.crateGetFederationMeta(
  inviteCode: inviteCode,
  federationId: federationId,
);

Future<FederationMeta> refreshFederationMeta({
  required FederationId federationId,
}) =>
    RustLib.instance.api.crateRefreshFederationMeta(federationId: federationId);

Future<List<Transaction>> transactions({
  required FederationId federationId,
  BigInt? timestamp,
  Uint8List? operationId,
  required List<String> modules,
}) => RustLib.instance.api.crateTransactions(
  federationId: federationId,
  timestamp: timestamp,
  operationId: operationId,
  modules: modules,
);

Future<OobNotesWrapper> sendEcash({
  required FederationId federationId,
  required BigInt amountMsats,
  required BigInt feeMsats,
}) => RustLib.instance.api.crateSendEcash(
  federationId: federationId,
  amountMsats: amountMsats,
  feeMsats: feeMsats,
);

/// Encrypt an ecash string for a tap-transfer recipient (Phase 1 of the NFC +
/// BLE "tap to send" feature). `recipient_pubkey` is the 33-byte compressed key
/// received over NFC; the returned blob is delivered to the receiver over BLE
/// and decrypted with `TapRecipient::decrypt`. See `tap_transfer.rs`.
Uint8List encryptEcashForTap({
  required String ecash,
  required List<int> recipientPubkey,
}) => RustLib.instance.api.crateEncryptEcashForTap(
  ecash: ecash,
  recipientPubkey: recipientPubkey,
);

Future<ReissueFees> calculateEcashReissueFees({
  required FederationId federationId,
  required String ecash,
}) => RustLib.instance.api.crateCalculateEcashReissueFees(
  federationId: federationId,
  ecash: ecash,
);

Future<EcashSendFees> calculateEcashSendFees({
  required FederationId federationId,
  required BigInt amountMsats,
}) => RustLib.instance.api.crateCalculateEcashSendFees(
  federationId: federationId,
  amountMsats: amountMsats,
);

Future<OperationId> reissueEcash({
  required FederationId federationId,
  required String ecash,
  required ReissueFees fees,
}) => RustLib.instance.api.crateReissueEcash(
  federationId: federationId,
  ecash: ecash,
  fees: fees,
);

/// Returns `(succeeded, amount_msats)`.
///
/// The bool is the outcome. `ReissueExternalNotesState` is a fedimint type that
/// FRB can only hand across as an opaque handle with no readable variants, so
/// returning it left Dart unable to tell success from failure — which is why the
/// redeem screen fell back to inferring the outcome from whether an amount came
/// back. The amount is `None` for reasons that have nothing to do with failure
/// (an internal reissue, or meta this build cannot read), so that inference
/// reported completed reissues as failures. Translating here keeps the typed
/// state on the Rust side, where the rest of the code still matches on it.
Future<(bool, BigInt?)> awaitEcashReissue({
  required FederationId federationId,
  required OperationId operationId,
}) => RustLib.instance.api.crateAwaitEcashReissue(
  federationId: federationId,
  operationId: operationId,
);

Future<bool> hasSeedPhraseAck() => RustLib.instance.api.crateHasSeedPhraseAck();

Future<void> ackSeedPhrase() => RustLib.instance.api.crateAckSeedPhrase();

Future<List<String>> wordList() => RustLib.instance.api.crateWordList();

Stream<DepositEventKind> subscribeDeposits({
  required FederationId federationId,
}) => RustLib.instance.api.crateSubscribeDeposits(federationId: federationId);

Future<(String, BigInt?)> allocateDepositAddress({
  required FederationId federationId,
}) => RustLib.instance.api.crateAllocateDepositAddress(
  federationId: federationId,
);

Future<PeginFeeQuote> getPeginFeeQuote({required FederationId federationId}) =>
    RustLib.instance.api.crateGetPeginFeeQuote(federationId: federationId);

Future<List<(FederationSelector, NWCConnectionInfo)>> getNwcConnectionInfo() =>
    RustLib.instance.api.crateGetNwcConnectionInfo();

Future<NWCConnectionInfo> setNwcConnectionInfo({
  required FederationId federationId,
  required String relay,
  required bool isDesktop,
}) => RustLib.instance.api.crateSetNwcConnectionInfo(
  federationId: federationId,
  relay: relay,
  isDesktop: isDesktop,
);

Future<void> removeNwcConnectionInfo({required FederationId federationId}) =>
    RustLib.instance.api.crateRemoveNwcConnectionInfo(
      federationId: federationId,
    );

/// Blocking NWC listener that runs until the connection is closed.
/// This is called directly from the foreground task.
/// Takes a string federation_id for easier passing from Dart foreground task.
Future<void> listenForNwcBlocking({required String federationIdStr}) => RustLib
    .instance
    .api
    .crateListenForNwcBlocking(federationIdStr: federationIdStr);

Future<List<(String, bool)>> getRelays() =>
    RustLib.instance.api.crateGetRelays();

Future<List<Utxo>> walletSummary({
  String? invite,
  FederationId? federationId,
}) => RustLib.instance.api.crateWalletSummary(
  invite: invite,
  federationId: federationId,
);

Stream<MultimintEvent> subscribeMultimintEvents() =>
    RustLib.instance.api.crateSubscribeMultimintEvents();

Future<String> federationIdToString({required FederationId federationId}) =>
    RustLib.instance.api.crateFederationIdToString(federationId: federationId);

Future<BigInt?> getBtcPrice() => RustLib.instance.api.crateGetBtcPrice();

Future<WithdrawFeesResponse> calculateWithdrawFees({
  required FederationId federationId,
  required String address,
  required BigInt amountSats,
}) => RustLib.instance.api.crateCalculateWithdrawFees(
  federationId: federationId,
  address: address,
  amountSats: amountSats,
);

Future<OperationId> withdrawToAddress({
  required FederationId federationId,
  required String address,
  required BigInt amountSats,
  required WithdrawFees fees,
  required BigInt federationFeeMsats,
}) => RustLib.instance.api.crateWithdrawToAddress(
  federationId: federationId,
  address: address,
  amountSats: amountSats,
  fees: fees,
  federationFeeMsats: federationFeeMsats,
);

Future<String> awaitWithdraw({
  required FederationId federationId,
  required OperationId operationId,
}) => RustLib.instance.api.crateAwaitWithdraw(
  federationId: federationId,
  operationId: operationId,
);

Future<BigInt> getMaxWithdrawableAmount({
  required FederationId federationId,
  required String address,
}) => RustLib.instance.api.crateGetMaxWithdrawableAmount(
  federationId: federationId,
  address: address,
);

Future<(int, int)> getModuleRecoveryProgress({
  required FederationId federationId,
  required RecoveryModule recoveryModule,
}) => RustLib.instance.api.crateGetModuleRecoveryProgress(
  federationId: federationId,
  recoveryModule: recoveryModule,
);

Stream<(int, int)> subscribeRecoveryProgress({
  required FederationId federationId,
  required RecoveryModule recoveryModule,
}) => RustLib.instance.api.crateSubscribeRecoveryProgress(
  federationId: federationId,
  recoveryModule: recoveryModule,
);

Future<(ParsedText, FederationSelector)> parseScannedTextForFederation({
  required String text,
  required FederationSelector federation,
}) => RustLib.instance.api.crateParseScannedTextForFederation(
  text: text,
  federation: federation,
);

Future<(ParsedText, FederationSelector?)> parsedScannedText({
  required String text,
}) => RustLib.instance.api.crateParsedScannedText(text: text);

Future<void> insertRelay({required String relayUri}) =>
    RustLib.instance.api.crateInsertRelay(relayUri: relayUri);

Future<void> removeRelay({required String relayUri}) =>
    RustLib.instance.api.crateRemoveRelay(relayUri: relayUri);

Future<List<(String, BigInt?, BigInt?)>> getAddresses({
  required FederationId federationId,
}) => RustLib.instance.api.crateGetAddresses(federationId: federationId);

Future<void> recheckAddress({
  required FederationId federationId,
  required BigInt tweakIdx,
}) => RustLib.instance.api.crateRecheckAddress(
  federationId: federationId,
  tweakIdx: tweakIdx,
);

Future<List<(BigInt, BigInt)>> getNoteSummary({
  required FederationId federationId,
}) => RustLib.instance.api.crateGetNoteSummary(federationId: federationId);

Future<List<FedimintGateway>> listGateways({
  String? invite,
  FederationId? federationId,
}) => RustLib.instance.api.crateListGateways(
  invite: invite,
  federationId: federationId,
);

Future<bool> checkEcashSpent({
  required FederationId federationId,
  required String ecash,
}) => RustLib.instance.api.crateCheckEcashSpent(
  federationId: federationId,
  ecash: ecash,
);

Future<List<String>> listLnAddressDomains({required String lnAddressApi}) =>
    RustLib.instance.api.crateListLnAddressDomains(lnAddressApi: lnAddressApi);

Future<LightningAddressConfig?> getLnAddressConfig({
  required FederationId federationId,
}) => RustLib.instance.api.crateGetLnAddressConfig(federationId: federationId);

Future<LNAddressStatus> checkLnAddressAvailability({
  required String username,
  required String domain,
  required String lnAddressApi,
  required String recurringdApi,
  required FederationId federationId,
}) => RustLib.instance.api.crateCheckLnAddressAvailability(
  username: username,
  domain: domain,
  lnAddressApi: lnAddressApi,
  recurringdApi: recurringdApi,
  federationId: federationId,
);

Future<void> registerLnAddress({
  required FederationId federationId,
  required String recurringdApi,
  required String lnAddressApi,
  required String username,
  required String domain,
}) => RustLib.instance.api.crateRegisterLnAddress(
  federationId: federationId,
  recurringdApi: recurringdApi,
  lnAddressApi: lnAddressApi,
  username: username,
  domain: domain,
);

Future<String> getInviteCode({
  required FederationId federationId,
  required int peer,
}) => RustLib.instance.api.crateGetInviteCode(
  federationId: federationId,
  peer: peer,
);

Future<bool> guardianLogin({
  required FederationId federationId,
  required int peer,
  required String password,
}) => RustLib.instance.api.crateGuardianLogin(
  federationId: federationId,
  peer: peer,
  password: password,
);

Future<GuardianAuditSummary> guardianAudit({
  required FederationId federationId,
  required int peer,
  required String password,
}) => RustLib.instance.api.crateGuardianAudit(
  federationId: federationId,
  peer: peer,
  password: password,
);

Future<GuardianBackupStatistics> guardianBackupStatistics({
  required FederationId federationId,
  required int peer,
  required String password,
}) => RustLib.instance.api.crateGuardianBackupStatistics(
  federationId: federationId,
  peer: peer,
  password: password,
);

Future<GuardianStatusSummary> guardianStatus({
  required FederationId federationId,
  required int peer,
  required String password,
}) => RustLib.instance.api.crateGuardianStatus(
  federationId: federationId,
  peer: peer,
  password: password,
);

Future<List<String>> guardianListGateways({
  required FederationId federationId,
  required int peer,
}) => RustLib.instance.api.crateGuardianListGateways(
  federationId: federationId,
  peer: peer,
);

Future<bool> guardianAddGateway({
  required FederationId federationId,
  required int peer,
  required String password,
  required String gatewayUrl,
}) => RustLib.instance.api.crateGuardianAddGateway(
  federationId: federationId,
  peer: peer,
  password: password,
  gatewayUrl: gatewayUrl,
);

Future<bool> guardianRemoveGateway({
  required FederationId federationId,
  required int peer,
  required String password,
  required String gatewayUrl,
}) => RustLib.instance.api.crateGuardianRemoveGateway(
  federationId: federationId,
  peer: peer,
  password: password,
  gatewayUrl: gatewayUrl,
);

Future<GuardianMetaState> guardianMetaState({
  required FederationId federationId,
  required int peer,
  required String password,
}) => RustLib.instance.api.crateGuardianMetaState(
  federationId: federationId,
  peer: peer,
  password: password,
);

Future<void> guardianMetaAccept({
  required FederationId federationId,
  required int peer,
  required String password,
  required String valueHex,
}) => RustLib.instance.api.crateGuardianMetaAccept(
  federationId: federationId,
  peer: peer,
  password: password,
  valueHex: valueHex,
);

Future<void> guardianMetaWithdraw({
  required FederationId federationId,
  required int peer,
  required String password,
}) => RustLib.instance.api.crateGuardianMetaWithdraw(
  federationId: federationId,
  peer: peer,
  password: password,
);

Future<void> guardianMetaProposeField({
  required FederationId federationId,
  required int peer,
  required String password,
  required String field,
  String? value,
}) => RustLib.instance.api.crateGuardianMetaProposeField(
  federationId: federationId,
  peer: peer,
  password: password,
  field: field,
  value: value,
);

Future<BitcoinDisplay> getBitcoinDisplay() =>
    RustLib.instance.api.crateGetBitcoinDisplay();

Future<void> setBitcoinDisplay({required BitcoinDisplay bitcoinDisplay}) =>
    RustLib.instance.api.crateSetBitcoinDisplay(bitcoinDisplay: bitcoinDisplay);

Future<FiatCurrency> getFiatCurrency() =>
    RustLib.instance.api.crateGetFiatCurrency();

Future<void> setFiatCurrency({required FiatCurrency fiatCurrency}) =>
    RustLib.instance.api.crateSetFiatCurrency(fiatCurrency: fiatCurrency);

Future<bool> getShowMsats() => RustLib.instance.api.crateGetShowMsats();

Future<void> setShowMsats({required bool showMsats}) =>
    RustLib.instance.api.crateSetShowMsats(showMsats: showMsats);

Future<bool> getTapReceiveEnabled() =>
    RustLib.instance.api.crateGetTapReceiveEnabled();

Future<void> setTapReceiveEnabled({required bool enabled}) =>
    RustLib.instance.api.crateSetTapReceiveEnabled(enabled: enabled);

Future<bool> hasPinCode() => RustLib.instance.api.crateHasPinCode();

/// Enroll a PIN for the first time.
///
/// Refuses to overwrite an existing one: changing a PIN has to prove knowledge
/// of the current one, which is what [`change_pin_code`] is for. Without this
/// check, anyone holding an unlocked phone could quietly replace the PIN.
Future<void> setPinCode({required String pin}) =>
    RustLib.instance.api.crateSetPinCode(pin: pin);

Future<void> changePinCode({
  required String currentPin,
  required String newPin,
}) => RustLib.instance.api.crateChangePinCode(
  currentPin: currentPin,
  newPin: newPin,
);

Future<bool> verifyPin({required String pin}) =>
    RustLib.instance.api.crateVerifyPin(pin: pin);

/// Seconds until PIN entry reopens after too many wrong guesses; `0` when it is
/// open. [`verify_pin`] returns `false` either way, so the UI reads this to tell
/// "wrong PIN" apart from "locked out" and to render the countdown.
Future<BigInt> pinLockoutSeconds() =>
    RustLib.instance.api.cratePinLockoutSeconds();

Future<void> clearPinCode({required String pin}) =>
    RustLib.instance.api.crateClearPinCode(pin: pin);

/// The ceiling on a single wallet-connect payment, in sats.
///
/// Returns the built-in default until the user changes it, so the UI shows what
/// is actually enforced rather than a blank.
Future<BigInt> getNwcMaxPaymentSats() =>
    RustLib.instance.api.crateGetNwcMaxPaymentSats();

/// The ceiling on everything wallet-connect spends in a day, in sats.
Future<BigInt> getNwcDailyBudgetSats() =>
    RustLib.instance.api.crateGetNwcDailyBudgetSats();

/// Set the ceiling on a single wallet-connect payment, in sats.
///
/// Rejects zero: a limit that refuses everything is indistinguishable from a
/// broken pairing from the client's side, and disconnecting is the way to stop
/// payments entirely.
Future<void> setNwcMaxPaymentSats({required BigInt sats}) =>
    RustLib.instance.api.crateSetNwcMaxPaymentSats(sats: sats);

/// Set the ceiling on everything wallet-connect spends in a day, in sats.
Future<void> setNwcDailyBudgetSats({required BigInt sats}) =>
    RustLib.instance.api.crateSetNwcDailyBudgetSats(sats: sats);

Future<bool> getRequirePinForSpending() =>
    RustLib.instance.api.crateGetRequirePinForSpending();

/// Toggle the spending PIN prompt.
///
/// Turning it *off* removes a protection, so it needs `current_pin`; turning it
/// on only adds one and does not. Otherwise brief access to an unlocked phone
/// would be enough to disable the prompt and then spend freely.
Future<void> setRequirePinForSpending({
  required bool require,
  String? currentPin,
}) => RustLib.instance.api.crateSetRequirePinForSpending(
  require: require,
  currentPin: currentPin,
);

Future<List<(FiatCurrency, BigInt)>?> getAllBtcPrices() =>
    RustLib.instance.api.crateGetAllBtcPrices();

Future<List<FederationId>?> getFederationOrder() =>
    RustLib.instance.api.crateGetFederationOrder();

Future<void> setFederationOrder({required List<FederationId> order}) =>
    RustLib.instance.api.crateSetFederationOrder(order: order);

Future<(String, String)> claimRandomLnAddress({
  required FederationId federationId,
  required String lnAddressApi,
  required String recurringdApi,
}) => RustLib.instance.api.crateClaimRandomLnAddress(
  federationId: federationId,
  lnAddressApi: lnAddressApi,
  recurringdApi: recurringdApi,
);

Future<void> leaveFederation({required FederationId federationId}) =>
    RustLib.instance.api.crateLeaveFederation(federationId: federationId);

Stream<List<PeerStatus>> subscribePeerStatus({
  String? invite,
  FederationId? federationId,
}) => RustLib.instance.api.crateSubscribePeerStatus(
  invite: invite,
  federationId: federationId,
);

/// Verify a NIP-05 identifier and return the associated npub
Future<String> verifyNip05({required String nip05Id}) =>
    RustLib.instance.api.crateVerifyNip05(nip05Id: nip05Id);

/// Check if contacts have been imported (first-time flag)
Future<bool> hasImportedContacts() =>
    RustLib.instance.api.crateHasImportedContacts();

/// Starts contact sync
Future<void> syncContacts({required String npub}) =>
    RustLib.instance.api.crateSyncContacts(npub: npub);

/// Clear all contacts and stop syncing
Future<BigInt> clearContactsAndStopSync() =>
    RustLib.instance.api.crateClearContactsAndStopSync();

/// Get all contacts, sorted by last_paid_at (recent first)
Future<List<Contact>> getAllContacts() =>
    RustLib.instance.api.crateGetAllContacts();

/// Get paginated contacts with cursor-based pagination
Future<List<Contact>> paginateContacts({
  BigInt? cursorLastPaidAt,
  BigInt? cursorCreatedAt,
  String? cursorNpub,
  required int limit,
}) => RustLib.instance.api.cratePaginateContacts(
  cursorLastPaidAt: cursorLastPaidAt,
  cursorCreatedAt: cursorCreatedAt,
  cursorNpub: cursorNpub,
  limit: limit,
);

/// Search contacts with pagination
Future<List<Contact>> paginateSearchContacts({
  required String query,
  BigInt? cursorLastPaidAt,
  BigInt? cursorCreatedAt,
  String? cursorNpub,
  required int limit,
}) => RustLib.instance.api.cratePaginateSearchContacts(
  query: query,
  cursorLastPaidAt: cursorLastPaidAt,
  cursorCreatedAt: cursorCreatedAt,
  cursorNpub: cursorNpub,
  limit: limit,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ClientConfig>>
abstract class ClientConfig implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Database>>
abstract class Database implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FederationId>>
abstract class FederationId implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SafeUrl>>
abstract class SafeUrl implements RustOpaqueInterface {}

@freezed
sealed class ParsedText with _$ParsedText {
  const ParsedText._();

  const factory ParsedText.inviteCode(String field0) = ParsedText_InviteCode;
  const factory ParsedText.inviteCodeWithEcash(String field0, String field1) =
      ParsedText_InviteCodeWithEcash;
  const factory ParsedText.lightningInvoice(String field0) =
      ParsedText_LightningInvoice;
  const factory ParsedText.bitcoinAddress(String field0, [BigInt? field1]) =
      ParsedText_BitcoinAddress;
  const factory ParsedText.ecash(BigInt field0) = ParsedText_Ecash;
  const factory ParsedText.lightningAddressOrLnurl(String field0) =
      ParsedText_LightningAddressOrLnurl;
  const factory ParsedText.ecashNoFederation() = ParsedText_EcashNoFederation;

  /// An `lnurlw://` URI converted to its `http(s)://` form, ready to fetch.
  const factory ParsedText.lnurlWithdraw(String field0) =
      ParsedText_LnurlWithdraw;
}
