// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'app_error.dart';
import 'db.dart';
import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'multimint.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `aggregate_recovery_progress`, `await_receive_lnv1`, `await_receive_lnv2`, `await_send_lnv1`, `await_send_lnv2`, `backup`, `build_client`, `cache_btc_price`, `cache_federation_meta`, `check_for_update`, `compute_send_fees`, `extract_recipient_pk_from_lnv2_lnurl`, `finish_active_subscriptions`, `from_peg_out_fees`, `get_client_database`, `get_client`, `get_ecash_amount_from_meta`, `get_federation`, `get_lnv1_amount_from_meta`, `get_lnv1_receive_tx`, `get_lnv1_send_tx`, `get_lnv2_amount_from_meta`, `get_mintv2_receive_amount`, `get_or_build_temp_client`, `get_recurringd_federations`, `get_url`, `gross_invoice_for_contract`, `guardian_admin_api`, `guardian_bitcoin_status`, `guardian_lnv2_module_api`, `guardian_meta_consensus`, `guardian_meta_module_api`, `guardian_meta_submit`, `init_recovery_progress_cache`, `invoice_is_loopback`, `is_invalid_guardian_auth`, `is_newer_version`, `join_federation_inner`, `join_federation_on`, `list_gateways`, `lnv1_update_gateway_cache`, `lnv2_gateways`, `load_clients`, `pay_lnv1`, `pay_lnv2`, `read_meta_msats`, `read_meta_string`, `read_meta_u64`, `read_meta_url`, `receive_lnv1`, `receive_lnv2`, `recovery_module_for_kind`, `register_federation`, `release_ln_address`, `remove_recovery_progress_cache`, `retire_recovery_client`, `run_cache_stage`, `run_migrations`, `send_federation_fee`, `shutdown_client`, `sign_challenge`, `skip_unrenderable`, `solve_gross_for_net`, `spawn_await_ecash_reissue`, `spawn_await_ecash_send`, `spawn_await_mintv2_receive`, `spawn_await_receive`, `spawn_await_recurringd_receive`, `spawn_await_send`, `spawn_await_withdraw`, `spawn_backfill_recipient_pk`, `spawn_cache_task`, `spawn_federation_teardown`, `spawn_lnv2_event_listener`, `spawn_recovery_progress`, `spawn_recurring_invoice_listener`, `update_recovery_progress_cache`, `validate_receive_fee`, `wait_for_recovery`, `wallet_network`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ClientType`, `JoinedFederation`, `LNAddressRegisterRequest`, `LNAddressRemoveRequest`, `OnChainWithdrawalMeta`, `WrappedEcash`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `cmp`, `consensus_decode_partial_from_finite_reader`, `consensus_decode_partial_from_finite_reader`, `consensus_decode_partial_from_finite_reader`, `consensus_encode`, `consensus_encode`, `consensus_encode`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `partial_cmp`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `federation_network`
// These functions have error during generation (see debug logs or enable `stop_on_error: true` for more details): `subscribe_peer_status`

OobNotesWrapper? parseOobNotes({required String notes}) =>
    RustLib.instance.api.crateMultimintParseOobNotes(notes: notes);

/// Returns true if `ecash` is mintv2 `ECash` (rather than walletv1 `OOBNotes`).
/// Used by the UI to gate features that only exist for walletv1, e.g. the
/// claim-status check, which mintv2 has no endpoint for yet.
bool isMintv2Ecash({required String ecash}) =>
    RustLib.instance.api.crateMultimintIsMintv2Ecash(ecash: ecash);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Amount>>
abstract class Amount implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Bolt11Invoice>>
abstract class Bolt11Invoice implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EcashAppResult < OOBNotesWrapper >>>
abstract class EcashAppResultOobNotesWrapper implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EcashAppResult < OperationId >>>
abstract class EcashAppResultOperationId implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EcashAppResult < SpendOOBState >>>
abstract class EcashAppResultSpendOobState implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EcashAppResult < String >>>
abstract class EcashAppResultString implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EcashAppResult < WithdrawFeesResponse >>>
abstract class EcashAppResultWithdrawFeesResponse
    implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EcashAppResult < u64 >>>
abstract class EcashAppResultU64 implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FederationMeta>>
abstract class FederationMeta implements RustOpaqueInterface {
  List<Guardian> get guardians;

  BigInt get lastUpdated;

  String? get lnaddressApi;

  String? get picture;

  String? get recurringdApi;

  FederationSelector get selector;

  String? get welcome;

  set guardians(List<Guardian> guardians);

  set lastUpdated(BigInt lastUpdated);

  set lnaddressApi(String? lnaddressApi);

  set picture(String? picture);

  set recurringdApi(String? recurringdApi);

  set selector(FederationSelector selector);

  set welcome(String? welcome);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FederationSelector>>
abstract class FederationSelector implements RustOpaqueInterface {
  FederationId get federationId;

  String get federationName;

  String? get network;

  set federationId(FederationId federationId);

  set federationName(String federationName);

  set network(String? network);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FinalReceiveOperationState>>
abstract class FinalReceiveOperationState implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Multimint>>
abstract class Multimint implements RustOpaqueInterface {
  Future<void> ackSeedPhrase();

  Future<(String, BigInt?)> allocateDepositAddress({
    required FederationId federationId,
  });

  Future<(ReissueExternalNotesState, BigInt?)> awaitEcashReissue({
    required FederationId federationId,
    required OperationId operationId,
  });

  Future<EcashAppResultSpendOobState> awaitEcashSend({
    required FederationId federationId,
    required OperationId operationId,
  });

  Future<(FinalReceiveOperationState, BigInt)> awaitReceive({
    required FederationId federationId,
    required OperationId operationId,
  });

  Future<LightningSendOutcome> awaitSend({
    required FederationId federationId,
    required OperationId operationId,
  });

  Future<EcashAppResultString> awaitWithdraw({
    required FederationId federationId,
    required OperationId operationId,
  });

  /// Fallible on purpose. The UI polls this, and both failure modes are
  /// ordinary rather than exceptional: the federation can be left while a
  /// screen still holds its id, and the balance query itself can fail
  /// transiently while a module is still coming up during recovery.
  ///
  /// Returning zero for either would be worse than an error — a wallet
  /// showing a confident zero is alarming and wrong.
  Future<BigInt> balance({required FederationId federationId});

  Future<ReissueFees> calculateEcashReissueFees({
    required FederationId federationId,
    required String ecash,
  });

  /// Quotes a [`Self::send_ecash`] of `amount_msats` without spending
  /// anything, returning both the *actual* amount the send will spend and the
  /// federation fee on top.
  ///
  /// Both mint modules round the requested amount up to a representable
  /// denomination before producing notes (mintv1 to the smallest economical
  /// denomination via `FeeConsensus::round_up`, mintv2 to a multiple of the
  /// smallest client denomination), so the actual amount can exceed what the
  /// user typed. We mirror that rounding here so the review screen shows the
  /// amount that will really be spent, then quote the fee at that amount.
  ///
  /// The fee comes from the same `send_fee_quote` both modules expose: zero
  /// when the wallet already holds exact-change notes (the send just hands
  /// them out), otherwise the cost of the self-reissue the send performs. The
  /// quote is point-in-time over the current note inventory and display-only.
  Future<EcashSendFees> calculateEcashSendFees({
    required FederationId federationId,
    required BigInt amountMsats,
  });

  Future<EcashAppResultWithdrawFeesResponse> calculateWithdrawFees({
    required FederationId federationId,
    required String address,
    required BigInt amountSats,
  });

  Future<bool> checkEcashSpent({
    required FederationId federationId,
    required String ecash,
  });

  Future<LNAddressStatus> checkLnAddressAvailability({
    required String username,
    required String domain,
    required String lnAddressApi,
    required String recurringdApi,
    required FederationId federationId,
  });

  Future<List<GatewayPaymentPreview>> computeAllGatewayPreviews({
    required FederationId federationId,
    required Amount amount,
    required Bolt11Invoice bolt11,
  });

  /// Computes the invoice amount and fee breakdown for a receive.
  ///
  /// When `include_fees` is true the fees are added on top of `amount`, so the
  /// sender covers them and exactly `amount` is credited to the receiver. When
  /// it is false the invoice equals `amount` exactly — the sender pays only what
  /// was requested and the receiver absorbs the fees, netting `amount` minus the
  /// fees. In both cases the returned `invoice_msats` is the invoice face value
  /// and the receiver nets `invoice_msats - federation_fee_msats -
  /// gateway_fee_msats`.
  Future<ReceiveAmount> computeReceiveAmountWithFees({
    required FederationId federationId,
    required SafeUrl gatewayUrl,
    required bool isLnv2,
    required Amount amount,
    required bool includeFees,
  });

  Future<bool> containsClient({required FederationId federationId});

  Future<List<(FederationSelector, bool)>> federations();

  Future<List<(String, BigInt?, BigInt?)>> getAddresses({
    required FederationId federationId,
  });

  Future<List<(FiatCurrency, BigInt)>?> getAllBtcPrices();

  Future<List<String>> getAllInviteCodes();

  Future<BitcoinDisplay> getBitcoinDisplay();

  Future<BigInt?> getBtcPrice();

  Future<FederationMeta> getCachedFederationMeta({
    String? invite,
    FederationId? federationId,
  });

  Future<List<FederationId>?> getFederationOrder();

  Future<FiatCurrency> getFiatCurrency();

  Future<String> getInviteCode({
    required FederationId federationId,
    required int peer,
  });

  /// Retreives currently configured Lightning Address
  Future<LightningAddressConfig?> getLnAddressConfig({
    required FederationId federationId,
  });

  Future<EcashAppResultU64> getMaxWithdrawableAmount({
    required FederationId federationId,
    required String address,
  });

  Future<List<String>> getMnemonic();

  Future<List<(BigInt, BigInt)>> getNoteSummary({
    required FederationId federationId,
  });

  Future<PeginFeeQuote> getPeginFeeQuote({required FederationId federationId});

  Future<RecoveryProgress> getRecoveryProgress({
    required FederationId federationId,
    required RecoveryModule recoveryModule,
  });

  Future<bool> getShowMsats();

  /// Returns false when the gateway was already whitelisted.
  Future<bool> guardianAddGateway({
    required FederationId federationId,
    required int peer,
    required String password,
    required String gatewayUrl,
  });

  Future<GuardianAuditSummary> guardianAudit({
    required FederationId federationId,
    required int peer,
    required String password,
  });

  Future<GuardianBackupStatistics> guardianBackupStatistics({
    required FederationId federationId,
    required int peer,
    required String password,
  });

  /// The lnv2 gateway whitelist is per-guardian state, so listing queries
  /// the given peer directly instead of the client's default strategy.
  Future<List<String>> guardianListGateways({
    required FederationId federationId,
    required int peer,
  });

  /// Verify guardian admin credentials against the `auth` endpoint, which
  /// succeeds only with the correct password. Returns `Ok(false)` on a
  /// rejected password (also the guardian's response when it has no admin
  /// password configured at all) and `Err` when the guardian is unreachable.
  Future<bool> guardianLogin({
    required FederationId federationId,
    required int peer,
    required String password,
  });

  /// Back an existing proposal by resubmitting its exact bytes.
  Future<void> guardianMetaAccept({
    required FederationId federationId,
    required int peer,
    required String password,
    required String valueHex,
  });

  /// Propose a single field change. The meta module stores one JSON document
  /// per key, so this reads the current consensus document, applies the edit
  /// and submits the whole document back. Passing `None` removes the field.
  Future<void> guardianMetaProposeField({
    required FederationId federationId,
    required int peer,
    required String password,
    required String field,
    String? value,
  });

  Future<GuardianMetaState> guardianMetaState({
    required FederationId federationId,
    required int peer,
    required String password,
  });

  /// Withdraw this guardian's vote by submitting the current consensus
  /// value, which is how the meta module expresses "no change".
  Future<void> guardianMetaWithdraw({
    required FederationId federationId,
    required int peer,
    required String password,
  });

  /// Returns false when the gateway was not whitelisted to begin with.
  Future<bool> guardianRemoveGateway({
    required FederationId federationId,
    required int peer,
    required String password,
    required String gatewayUrl,
  });

  Future<GuardianStatusSummary> guardianStatus({
    required FederationId federationId,
    required int peer,
    required String password,
  });

  Future<bool> hasSeedPhraseAck();

  Future<FederationSelector> joinFederation({
    required String invite,
    required bool recover,
  });

  /// Leaves a federation.
  ///
  /// Returns as soon as the federation is gone from the app's point of view:
  /// its config row is deleted, its client is out of the map, and its task
  /// group has been detached, so nothing can route to it or spawn onto it any
  /// more. The teardown that actually takes time — cancelling the
  /// federation's background tasks, waiting for them to release their client
  /// references, and shutting the client down so its own executor stops —
  /// runs on a detached task afterwards. Leaving should never make the user
  /// watch a spinner.
  ///
  /// Every other persisted row is deliberately kept. The client database, the
  /// Lightning Address registration, the NWC pairing and the cached metadata
  /// are all reused if the user joins this federation again.
  Future<void> leaveFederation({required FederationId federationId});

  /// Computes the largest amount (in msats) the user can pay over Lightning
  /// out of this federation's balance through `gateway`, accounting for that
  /// gateway's routing fee (added on top of the invoice) and the
  /// on-federation send fee. This is the amount to request an invoice for in
  /// order to spend (close to) the whole balance, and backs the "Max" button
  /// when paying a Lightning Address / LNURL where the user chooses the amount
  /// and the gateway.
  ///
  /// `is_lnv2` selects which module to quote against — the same gateway the
  /// user picked on the number pad and will pay through — so the result is
  /// deterministic instead of relying on auto-selection. Pinning the gateway
  /// also avoids the guardian gateway-list lookup: LNv2 makes a single
  /// `routing_info` call to that gateway, and LNv1 quotes entirely locally
  /// against its cached announcement. The quote is point-in-time (it moves
  /// with the balance); the eventual send remains the source of truth and may
  /// still fail if the balance or gateway state changes in between.
  ///
  /// `loopback` picks the fee schedule: `false` charges the gateway's default
  /// send fee for a payment routed over Lightning, `true` the cheap
  /// no-Lightning-hop fee — `send_fee_minimum` for LNv2, and for LNv1 no
  /// routing fee at all, since an internal payment has no gateway in the
  /// path. It is a caller's decision because it is a property of the invoice,
  /// not of the balance: see [`Self::probe_invoice_is_loopback`], which
  /// answers it from a throwaway invoice before the real amount is chosen.
  Future<BigInt> maxLightningSend({
    required FederationId federationId,
    required SafeUrl gateway,
    required bool isLnv2,
    required bool loopback,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<Multimint> newInstance({
    required Database db,
    required MultimintCreation creationType,
  }) => RustLib.instance.api.crateMultimintMultimintNew(
    db: db,
    creationType: creationType,
  );

  Future<BigInt> parseEcash({
    required FederationId federationId,
    required OobNotes notes,
  });

  /// Whether an invoice would be paid without a Lightning hop through the
  /// single gateway the user picked, without pricing every other gateway the
  /// way [`Self::compute_all_gateway_previews`] does.
  ///
  /// Backs the "Max" button's probe: the amount has to be chosen before the
  /// real invoice is requested, so a throwaway invoice is fetched first just
  /// to answer this question and pick the right fee schedule.
  Future<bool> probeInvoiceIsLoopback({
    required FederationId federationId,
    required SafeUrl gateway,
    required bool isLnv2,
    required Bolt11Invoice invoice,
  });

  Future<(Bolt11Invoice, OperationId)> receive({
    required FederationId federationId,
    required BigInt amountMsatsWithFees,
    required BigInt amountMsatsWithoutFees,
    required BigInt federationFeeMsats,
    required BigInt gatewayFeeMsats,
    required SafeUrl gateway,
    required bool isLnv2,
  });

  Future<void> recheckAddress({
    required FederationId federationId,
    required BigInt tweakIdx,
  });

  /// Attempt to recover a Lightning Address after wallet recovery.
  /// Uses the deterministic recipient_pk to reverse-lookup on the lnaddr server.
  Future<void> recoverLnAddress({
    required FederationId federationId,
    required String lnAddressApi,
    required String recurringdApi,
  });

  /// Pre-warm guardian connections for every joined federation.
  ///
  /// On Android, sockets to guardians often drop while the app is
  /// backgrounded and don't reconnect on their own. Calling this on app
  /// resume kicks off one connection attempt per peer per federation;
  /// already-live connections are no-ops and failures back off internally.
  Future<void> refreshConnections();

  /// Refetch and re-cache a federation's meta immediately, bypassing both the
  /// cached value and the periodic refresh task. Used after a guardian action
  /// changes meta consensus, so the app reflects it without waiting out the
  /// cache interval.
  Future<FederationMeta> refreshFederationMeta({
    required FederationId federationId,
  });

  /// Register LNURL/LN Address
  Future<void> registerLnAddress({
    required FederationId federationId,
    required String recurringdApi,
    required String lnAddressApi,
    required String username,
    required String domain,
  });

  Future<EcashAppResultOperationId> reissueEcash({
    required FederationId federationId,
    required String ecash,
    required ReissueFees fees,
  });

  Future<void> rejoinFromBackupInvites({
    required List<String> backupInviteCodes,
  });

  Future<EcashAppResultOperationId> send({
    required FederationId federationId,
    required String invoice,
    required SafeUrl gateway,
    required bool isLnv2,
    required BigInt amountWithFees,
    required BigInt federationFeeMsats,
    required BigInt gatewayFeeMsats,
    String? lnAddress,
  });

  Future<EcashAppResultOobNotesWrapper> sendEcash({
    required FederationId federationId,
    required BigInt amountMsats,
    required BigInt feeMsats,
  });

  Future<void> setBitcoinDisplay({required BitcoinDisplay bitcoinDisplay});

  Future<void> setFederationOrder({required List<FederationId> order});

  Future<void> setFiatCurrency({required FiatCurrency fiatCurrency});

  Future<void> setShowMsats({required bool showMsats});

  Future<List<Transaction>> transactions({
    required FederationId federationId,
    BigInt? timestamp,
    Uint8List? operationId,
    required List<String> modules,
  });

  Future<List<Utxo>> walletSummary({
    String? invite,
    FederationId? federationId,
  });

  Future<EcashAppResultOperationId> withdrawToAddress({
    required FederationId federationId,
    required String address,
    required BigInt amountSats,
    required WithdrawFees fees,
    required BigInt federationFeeMsats,
  });
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<OOBNotes>>
abstract class OobNotes implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<OOBNotesWrapper>>
abstract class OobNotesWrapper implements RustOpaqueInterface {
  BigInt amountMsats();

  @override
  String toString();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<OperationId>>
abstract class OperationId implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RecoveryProgress>>
abstract class RecoveryProgress implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ReissueExternalNotesState>>
abstract class ReissueExternalNotesState implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WithdrawFees>>
abstract class WithdrawFees implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WithdrawFeesResponse>>
abstract class WithdrawFeesResponse implements RustOpaqueInterface {
  BigInt get federationFeeMsats;

  BigInt get feeAmount;

  double get feeRateSatsPerVb;

  WithdrawFees get fees;

  int get txSizeVbytes;

  set federationFeeMsats(BigInt federationFeeMsats);

  set feeAmount(BigInt feeAmount);

  set feeRateSatsPerVb(double feeRateSatsPerVb);

  set fees(WithdrawFees fees);

  set txSizeVbytes(int txSizeVbytes);
}

class AwaitingConfsEvent {
  final BigInt amount;
  final String outpoint;
  final BigInt blockHeight;
  final BigInt needed;
  final String? txid;

  const AwaitingConfsEvent({
    required this.amount,
    required this.outpoint,
    required this.blockHeight,
    required this.needed,
    this.txid,
  });

  @override
  int get hashCode =>
      amount.hashCode ^
      outpoint.hashCode ^
      blockHeight.hashCode ^
      needed.hashCode ^
      txid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AwaitingConfsEvent &&
          runtimeType == other.runtimeType &&
          amount == other.amount &&
          outpoint == other.outpoint &&
          blockHeight == other.blockHeight &&
          needed == other.needed &&
          txid == other.txid;
}

class ClaimedEvent {
  final BigInt amount;
  final String outpoint;
  final String? txid;

  const ClaimedEvent({required this.amount, required this.outpoint, this.txid});

  @override
  int get hashCode => amount.hashCode ^ outpoint.hashCode ^ txid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClaimedEvent &&
          runtimeType == other.runtimeType &&
          amount == other.amount &&
          outpoint == other.outpoint &&
          txid == other.txid;
}

class ConfirmedEvent {
  final BigInt amount;
  final String outpoint;
  final String? txid;

  const ConfirmedEvent({
    required this.amount,
    required this.outpoint,
    this.txid,
  });

  @override
  int get hashCode => amount.hashCode ^ outpoint.hashCode ^ txid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConfirmedEvent &&
          runtimeType == other.runtimeType &&
          amount == other.amount &&
          outpoint == other.outpoint &&
          txid == other.txid;
}

@freezed
sealed class ContactSyncEventKind with _$ContactSyncEventKind {
  const ContactSyncEventKind._();

  const factory ContactSyncEventKind.started() = ContactSyncEventKind_Started;
  const factory ContactSyncEventKind.progress({required BigInt synced}) =
      ContactSyncEventKind_Progress;
  const factory ContactSyncEventKind.completed({
    required BigInt added,
    required BigInt updated,
    required BigInt removed,
  }) = ContactSyncEventKind_Completed;
  const factory ContactSyncEventKind.error(String field0) =
      ContactSyncEventKind_Error;
}

@freezed
sealed class DepositEventKind with _$DepositEventKind {
  const DepositEventKind._();

  const factory DepositEventKind.mempool(MempoolEvent field0) =
      DepositEventKind_Mempool;
  const factory DepositEventKind.awaitingConfs(AwaitingConfsEvent field0) =
      DepositEventKind_AwaitingConfs;
  const factory DepositEventKind.confirmed(ConfirmedEvent field0) =
      DepositEventKind_Confirmed;
  const factory DepositEventKind.claimed(ClaimedEvent field0) =
      DepositEventKind_Claimed;
}

/// Quote for an ecash send. `amount_msats` is the *actual* amount the send will
/// spend on the ecash: the requested amount rounded up to a representable
/// denomination, which both mint modules do before producing notes, so it can
/// exceed what the user typed. `fee_msats` is the federation fee charged on top.
/// The total debited from the wallet is `amount_msats + fee_msats`.
class EcashSendFees {
  final BigInt amountMsats;
  final BigInt feeMsats;

  const EcashSendFees({required this.amountMsats, required this.feeMsats});

  @override
  int get hashCode => amountMsats.hashCode ^ feeMsats.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EcashSendFees &&
          runtimeType == other.runtimeType &&
          amountMsats == other.amountMsats &&
          feeMsats == other.feeMsats;
}

class FedimintGateway {
  final String endpoint;
  final BigInt baseRoutingFee;
  final BigInt ppmRoutingFee;
  final BigInt baseTransactionFee;
  final BigInt ppmTransactionFee;
  final String? lightningAlias;
  final String? lightningNode;
  final bool isLnv2;
  final bool isVettted;

  /// LNv1 only: short_channel_id used in route hints to identify the federation.
  /// Used to detect "loopback" invoices issued by the same federation, which
  /// incur zero gateway routing fees.
  final BigInt? federationIndex;

  /// LNv2 only: gateway's minimum send fee, applied on loopback payments
  /// (where the invoice's payee is the gateway's own Lightning node).
  final BigInt? minBaseRoutingFee;
  final BigInt? minPpmRoutingFee;

  const FedimintGateway({
    required this.endpoint,
    required this.baseRoutingFee,
    required this.ppmRoutingFee,
    required this.baseTransactionFee,
    required this.ppmTransactionFee,
    this.lightningAlias,
    this.lightningNode,
    required this.isLnv2,
    required this.isVettted,
    this.federationIndex,
    this.minBaseRoutingFee,
    this.minPpmRoutingFee,
  });

  @override
  int get hashCode =>
      endpoint.hashCode ^
      baseRoutingFee.hashCode ^
      ppmRoutingFee.hashCode ^
      baseTransactionFee.hashCode ^
      ppmTransactionFee.hashCode ^
      lightningAlias.hashCode ^
      lightningNode.hashCode ^
      isLnv2.hashCode ^
      isVettted.hashCode ^
      federationIndex.hashCode ^
      minBaseRoutingFee.hashCode ^
      minPpmRoutingFee.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FedimintGateway &&
          runtimeType == other.runtimeType &&
          endpoint == other.endpoint &&
          baseRoutingFee == other.baseRoutingFee &&
          ppmRoutingFee == other.ppmRoutingFee &&
          baseTransactionFee == other.baseTransactionFee &&
          ppmTransactionFee == other.ppmTransactionFee &&
          lightningAlias == other.lightningAlias &&
          lightningNode == other.lightningNode &&
          isLnv2 == other.isLnv2 &&
          isVettted == other.isVettted &&
          federationIndex == other.federationIndex &&
          minBaseRoutingFee == other.minBaseRoutingFee &&
          minPpmRoutingFee == other.minPpmRoutingFee;
}

class GatewayPaymentPreview {
  final FedimintGateway gateway;
  final BigInt amountWithFees;

  /// Gateway off-chain routing fee (baked into the outgoing contract).
  final BigInt gatewayFee;

  /// On-federation fee: lightning output fee + mint funding/change fees +
  /// dust, quoted via the lightning module's `send_fee_quote`.
  final BigInt federationFee;

  const GatewayPaymentPreview({
    required this.gateway,
    required this.amountWithFees,
    required this.gatewayFee,
    required this.federationFee,
  });

  @override
  int get hashCode =>
      gateway.hashCode ^
      amountWithFees.hashCode ^
      gatewayFee.hashCode ^
      federationFee.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GatewayPaymentPreview &&
          runtimeType == other.runtimeType &&
          gateway == other.gateway &&
          amountWithFees == other.amountWithFees &&
          gatewayFee == other.gatewayFee &&
          federationFee == other.federationFee;
}

class Guardian {
  final int peerId;
  final String name;
  final String? version;

  const Guardian({required this.peerId, required this.name, this.version});

  @override
  int get hashCode => peerId.hashCode ^ name.hashCode ^ version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Guardian &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          name == other.name &&
          version == other.version;
}

class GuardianAuditSummary {
  final PlatformInt64 netAssetsMsats;
  final List<GuardianModuleSummary> moduleSummaries;

  const GuardianAuditSummary({
    required this.netAssetsMsats,
    required this.moduleSummaries,
  });

  @override
  int get hashCode => netAssetsMsats.hashCode ^ moduleSummaries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GuardianAuditSummary &&
          runtimeType == other.runtimeType &&
          netAssetsMsats == other.netAssetsMsats &&
          moduleSummaries == other.moduleSummaries;
}

class GuardianBackupStatistics {
  final BigInt numBackups;
  final BigInt totalSizeBytes;
  final BigInt refreshed1D;
  final BigInt refreshed1W;
  final BigInt refreshed1M;
  final BigInt refreshed3M;

  const GuardianBackupStatistics({
    required this.numBackups,
    required this.totalSizeBytes,
    required this.refreshed1D,
    required this.refreshed1W,
    required this.refreshed1M,
    required this.refreshed3M,
  });

  @override
  int get hashCode =>
      numBackups.hashCode ^
      totalSizeBytes.hashCode ^
      refreshed1D.hashCode ^
      refreshed1W.hashCode ^
      refreshed1M.hashCode ^
      refreshed3M.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GuardianBackupStatistics &&
          runtimeType == other.runtimeType &&
          numBackups == other.numBackups &&
          totalSizeBytes == other.totalSizeBytes &&
          refreshed1D == other.refreshed1D &&
          refreshed1W == other.refreshed1W &&
          refreshed1M == other.refreshed1M &&
          refreshed3M == other.refreshed3M;
}

class GuardianBitcoinStatus {
  /// Backend kind and credential-stripped URL; None when the authenticated
  /// `bitcoin_rpc_config` endpoint is unavailable on this guardian.
  final String? kind;
  final String? url;
  final BigInt consensusBlockCount;

  /// This guardian's own bitcoin node height; comparing it against the
  /// consensus count reveals a node that has fallen behind. Wallet v1 only.
  final BigInt? localBlockCount;

  /// Consensus fee rate in sats per kvB. Wallet v2 only.
  final BigInt? consensusFeerateSatsPerKvb;

  const GuardianBitcoinStatus({
    this.kind,
    this.url,
    required this.consensusBlockCount,
    this.localBlockCount,
    this.consensusFeerateSatsPerKvb,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      url.hashCode ^
      consensusBlockCount.hashCode ^
      localBlockCount.hashCode ^
      consensusFeerateSatsPerKvb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GuardianBitcoinStatus &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          url == other.url &&
          consensusBlockCount == other.consensusBlockCount &&
          localBlockCount == other.localBlockCount &&
          consensusFeerateSatsPerKvb == other.consensusFeerateSatsPerKvb;
}

class GuardianHealth {
  final bool consensusRunning;

  /// Raw server status, shown when consensus is not running (e.g. during
  /// setup or an upgrade).
  final String serverStatus;
  final BigInt? sessionCount;
  final BigInt peersOnline;
  final BigInt peersTotal;
  final BigInt? consensusOrdLatencyMs;
  final BigInt? scheduledShutdownSession;

  const GuardianHealth({
    required this.consensusRunning,
    required this.serverStatus,
    this.sessionCount,
    required this.peersOnline,
    required this.peersTotal,
    this.consensusOrdLatencyMs,
    this.scheduledShutdownSession,
  });

  @override
  int get hashCode =>
      consensusRunning.hashCode ^
      serverStatus.hashCode ^
      sessionCount.hashCode ^
      peersOnline.hashCode ^
      peersTotal.hashCode ^
      consensusOrdLatencyMs.hashCode ^
      scheduledShutdownSession.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GuardianHealth &&
          runtimeType == other.runtimeType &&
          consensusRunning == other.consensusRunning &&
          serverStatus == other.serverStatus &&
          sessionCount == other.sessionCount &&
          peersOnline == other.peersOnline &&
          peersTotal == other.peersTotal &&
          consensusOrdLatencyMs == other.consensusOrdLatencyMs &&
          scheduledShutdownSession == other.scheduledShutdownSession;
}

/// A pending meta submission, grouped across every guardian that submitted
/// this exact value.
class GuardianMetaProposal {
  final Uint16List peerIds;

  /// The raw submitted bytes, hex encoded. Accepting a proposal must
  /// resubmit these exact bytes: consensus only forms over byte-identical
  /// values, so re-serializing the parsed document could silently never
  /// converge.
  final String valueHex;

  /// The submission parsed as JSON, or None when a guardian submitted
  /// something that is not valid JSON.
  final String? valueJson;

  /// Whether the guardian we are logged into is backing this value.
  final bool isOurs;

  const GuardianMetaProposal({
    required this.peerIds,
    required this.valueHex,
    this.valueJson,
    required this.isOurs,
  });

  @override
  int get hashCode =>
      peerIds.hashCode ^
      valueHex.hashCode ^
      valueJson.hashCode ^
      isOurs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GuardianMetaProposal &&
          runtimeType == other.runtimeType &&
          peerIds == other.peerIds &&
          valueHex == other.valueHex &&
          valueJson == other.valueJson &&
          isOurs == other.isOurs;
}

class GuardianMetaState {
  /// The current agreed meta document as JSON, absent until a first
  /// consensus forms.
  final String? consensusJson;
  final BigInt? revision;
  final List<GuardianMetaProposal> proposals;

  /// How many guardians must submit an identical value for it to become the
  /// new consensus.
  final int threshold;
  final int totalGuardians;

  const GuardianMetaState({
    this.consensusJson,
    this.revision,
    required this.proposals,
    required this.threshold,
    required this.totalGuardians,
  });

  @override
  int get hashCode =>
      consensusJson.hashCode ^
      revision.hashCode ^
      proposals.hashCode ^
      threshold.hashCode ^
      totalGuardians.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GuardianMetaState &&
          runtimeType == other.runtimeType &&
          consensusJson == other.consensusJson &&
          revision == other.revision &&
          proposals == other.proposals &&
          threshold == other.threshold &&
          totalGuardians == other.totalGuardians;
}

class GuardianModuleSummary {
  final int moduleInstanceId;
  final String kind;

  /// Positive means assets, negative means liabilities (e.g. the mint
  /// module's outstanding e-cash).
  final PlatformInt64 netAssetsMsats;

  const GuardianModuleSummary({
    required this.moduleInstanceId,
    required this.kind,
    required this.netAssetsMsats,
  });

  @override
  int get hashCode =>
      moduleInstanceId.hashCode ^ kind.hashCode ^ netAssetsMsats.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GuardianModuleSummary &&
          runtimeType == other.runtimeType &&
          moduleInstanceId == other.moduleInstanceId &&
          kind == other.kind &&
          netAssetsMsats == other.netAssetsMsats;
}

class GuardianStatusSummary {
  final GuardianHealth health;

  /// None when the federation has no wallet module.
  final GuardianBitcoinStatus? bitcoin;

  /// Whether the federation runs the lnv2 module, i.e. whether gateway
  /// management is available.
  final bool hasLnv2;

  /// Whether the federation runs the meta module, i.e. whether federation
  /// settings can be viewed and proposed.
  final bool hasMeta;

  const GuardianStatusSummary({
    required this.health,
    this.bitcoin,
    required this.hasLnv2,
    required this.hasMeta,
  });

  @override
  int get hashCode =>
      health.hashCode ^ bitcoin.hashCode ^ hasLnv2.hashCode ^ hasMeta.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GuardianStatusSummary &&
          runtimeType == other.runtimeType &&
          health == other.health &&
          bitcoin == other.bitcoin &&
          hasLnv2 == other.hasLnv2 &&
          hasMeta == other.hasMeta;
}

class InvoicePaidEvent {
  final BigInt amountMsats;

  const InvoicePaidEvent({required this.amountMsats});

  @override
  int get hashCode => amountMsats.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InvoicePaidEvent &&
          runtimeType == other.runtimeType &&
          amountMsats == other.amountMsats;
}

@freezed
sealed class LightningEventKind with _$LightningEventKind {
  const LightningEventKind._();

  const factory LightningEventKind.invoicePaid(InvoicePaidEvent field0) =
      LightningEventKind_InvoicePaid;
  const factory LightningEventKind.paymentSent() =
      LightningEventKind_PaymentSent;
}

@freezed
sealed class LightningSendOutcome with _$LightningSendOutcome {
  const LightningSendOutcome._();

  const factory LightningSendOutcome.success(String field0) =
      LightningSendOutcome_Success;

  /// Carries the typed reason for the failure so the Dart layer can render
  /// a localized message on the Failure screen.
  const factory LightningSendOutcome.failure(EcashAppError field0) =
      LightningSendOutcome_Failure;
}

@freezed
sealed class LNAddressStatus with _$LNAddressStatus {
  const LNAddressStatus._();

  const factory LNAddressStatus.registered({required String lnurl}) =
      LNAddressStatus_Registered;
  const factory LNAddressStatus.available() = LNAddressStatus_Available;
  const factory LNAddressStatus.currentConfig() = LNAddressStatus_CurrentConfig;
  const factory LNAddressStatus.unsupportedFederation() =
      LNAddressStatus_UnsupportedFederation;
  const factory LNAddressStatus.invalid() = LNAddressStatus_Invalid;
}

enum LogLevel { trace, debug, info, warn, error }

class MempoolEvent {
  final BigInt amount;

  /// The `txid:vout` of the deposit, used by the UI to group every event
  /// describing it onto one row.
  ///
  /// walletv2 falls back to the receive address for a deposit a federation
  /// reported without an outpoint (see `spawn_v2_deposit_event_listener`), so
  /// `txid` rather than this field is the source for display purposes.
  final String outpoint;
  final String? txid;

  const MempoolEvent({required this.amount, required this.outpoint, this.txid});

  @override
  int get hashCode => amount.hashCode ^ outpoint.hashCode ^ txid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MempoolEvent &&
          runtimeType == other.runtimeType &&
          amount == other.amount &&
          outpoint == other.outpoint &&
          txid == other.txid;
}

@freezed
sealed class MultimintCreation with _$MultimintCreation {
  const MultimintCreation._();

  const factory MultimintCreation.new_() = MultimintCreation_New;
  const factory MultimintCreation.loadExisting() =
      MultimintCreation_LoadExisting;
  const factory MultimintCreation.newFromMnemonic({
    required List<String> words,
  }) = MultimintCreation_NewFromMnemonic;
}

@freezed
sealed class MultimintEvent with _$MultimintEvent {
  const MultimintEvent._();

  const factory MultimintEvent.deposit(
    (FederationId, DepositEventKind) field0,
  ) = MultimintEvent_Deposit;
  const factory MultimintEvent.lightning(
    (FederationId, LightningEventKind) field0,
  ) = MultimintEvent_Lightning;
  const factory MultimintEvent.log(LogLevel field0, String field1) =
      MultimintEvent_Log;
  const factory MultimintEvent.recoveryDone(String field0) =
      MultimintEvent_RecoveryDone;
  const factory MultimintEvent.recoveryProgress(
    String field0,
    RecoveryModule field1,
    int field2,
    int field3,
  ) = MultimintEvent_RecoveryProgress;
  const factory MultimintEvent.ecash((FederationId, BigInt) field0) =
      MultimintEvent_Ecash;
  const factory MultimintEvent.nostrRecovery(
    String field0,
    int field1, [
    FederationSelector? field2,
  ]) = MultimintEvent_NostrRecovery;
  const factory MultimintEvent.nostrRelayStatus(
    String field0,
    RelayStatusKind field1,
  ) = MultimintEvent_NostrRelayStatus;
  const factory MultimintEvent.nostrRecoveryPhase(NostrRecoveryPhase field0) =
      MultimintEvent_NostrRecoveryPhase;
  const factory MultimintEvent.contactSync(ContactSyncEventKind field0) =
      MultimintEvent_ContactSync;
  const factory MultimintEvent.updateAvailable(String field0) =
      MultimintEvent_UpdateAvailable;

  /// A federation's cached meta changed (name, picture, welcome message or
  /// guardians), so screens holding it should reload. Carries the federation
  /// id as a string: a bare opaque type as an enum payload makes the bridge
  /// generate the whole enum as opaque, breaking every other variant.
  const factory MultimintEvent.metaUpdated(String field0) =
      MultimintEvent_MetaUpdated;

  /// Structured payment-flow error. The Dart layer auto-surfaces these as
  /// localized error toasts (see `lib/app.dart` and `lib/error_helper.dart`).
  const factory MultimintEvent.paymentError(
    (FederationId, EcashAppError) field0,
  ) = MultimintEvent_PaymentError;
}

@freezed
sealed class NostrRecoveryPhase with _$NostrRecoveryPhase {
  const NostrRecoveryPhase._();

  const factory NostrRecoveryPhase.connectingToRelays() =
      NostrRecoveryPhase_ConnectingToRelays;
  const factory NostrRecoveryPhase.fetchingBackup() =
      NostrRecoveryPhase_FetchingBackup;
  const factory NostrRecoveryPhase.decryptingInvites() =
      NostrRecoveryPhase_DecryptingInvites;
  const factory NostrRecoveryPhase.rejoiningFederations(int field0) =
      NostrRecoveryPhase_RejoiningFederations;

  /// The relays returned nothing to restore.
  ///
  /// Distinct from `RejoiningFederations(0)` so the UI cannot render "found
  /// nothing" the same way it renders "restored everything". The nostr backup
  /// is best effort — relays prune, and the seed phrase is the real backup —
  /// so an empty result is an ordinary outcome the user has to be told about,
  /// because rejoining then needs invite codes they must supply themselves.
  const factory NostrRecoveryPhase.noBackupFound() =
      NostrRecoveryPhase_NoBackupFound;
}

class PaymentPreviewWithGateways {
  final BigInt amountMsats;
  final String paymentHash;
  final String network;
  final String invoice;
  final List<GatewayPaymentPreview> gatewayPreviews;
  final BigInt selectedIndex;

  const PaymentPreviewWithGateways({
    required this.amountMsats,
    required this.paymentHash,
    required this.network,
    required this.invoice,
    required this.gatewayPreviews,
    required this.selectedIndex,
  });

  @override
  int get hashCode =>
      amountMsats.hashCode ^
      paymentHash.hashCode ^
      network.hashCode ^
      invoice.hashCode ^
      gatewayPreviews.hashCode ^
      selectedIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PaymentPreviewWithGateways &&
          runtimeType == other.runtimeType &&
          amountMsats == other.amountMsats &&
          paymentHash == other.paymentHash &&
          network == other.network &&
          invoice == other.invoice &&
          gatewayPreviews == other.gatewayPreviews &&
          selectedIndex == other.selectedIndex;
}

enum PeerConnectivity { direct, relay, mixed, tor, unknown }

class PeerStatus {
  final int peerId;
  final String name;
  final bool online;
  final PeerConnectivity connectivity;
  final String url;

  /// Guardian's reported `fedimintd` version. Travels with the peer status so
  /// the UI reflects guardian upgrades in real time (a guardian upgrade
  /// restarts fedimintd, which surfaces as a reconnect on the status stream).
  final String? version;

  const PeerStatus({
    required this.peerId,
    required this.name,
    required this.online,
    required this.connectivity,
    required this.url,
    this.version,
  });

  @override
  int get hashCode =>
      peerId.hashCode ^
      name.hashCode ^
      online.hashCode ^
      connectivity.hashCode ^
      url.hashCode ^
      version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeerStatus &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          name == other.name &&
          online == other.online &&
          connectivity == other.connectivity &&
          url == other.url &&
          version == other.version;
}

/// Fee parameters for an on-chain deposit (peg-in). We can't quote an exact
/// charge up front because the deposit amount is unknown, and for walletv2 the
/// federation fee scales with the amount, so we surface the parameters instead.
class PeginFeeQuote {
  /// Constant federation fee charged on the deposit, in msats.
  /// walletv1: `peg_in_abs`; walletv2: `fee_consensus.base`.
  final BigInt baseFeeMsats;

  /// Relative federation fee in parts-per-million (walletv2 only; 0 for walletv1).
  final BigInt partsPerMillion;

  /// Dynamic on-chain claim/sweep fee in sats (walletv2 only; `None` for
  /// walletv1 or when no consensus feerate is currently available).
  final BigInt? onchainClaimFeeSats;

  const PeginFeeQuote({
    required this.baseFeeMsats,
    required this.partsPerMillion,
    this.onchainClaimFeeSats,
  });

  @override
  int get hashCode =>
      baseFeeMsats.hashCode ^
      partsPerMillion.hashCode ^
      onchainClaimFeeSats.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeginFeeQuote &&
          runtimeType == other.runtimeType &&
          baseFeeMsats == other.baseFeeMsats &&
          partsPerMillion == other.partsPerMillion &&
          onchainClaimFeeSats == other.onchainClaimFeeSats;
}

/// Result of pricing a Lightning receive. `invoice_msats` is the invoice's face
/// value (what the payer pays). The fee is broken out into its two sources:
/// `federation_fee_msats` (on-federation: lightning input fee plus mint output
/// fees plus dust) and `gateway_fee_msats` (the gateway's off-chain routing fee,
/// always 0 for LNv1). The receiver is credited
/// `invoice_msats - federation_fee_msats - gateway_fee_msats`. Both are quoted at
/// `invoice_msats`, not the requested amount, so they match what is really
/// deducted.
class ReceiveAmount {
  final BigInt invoiceMsats;
  final BigInt federationFeeMsats;
  final BigInt gatewayFeeMsats;

  const ReceiveAmount({
    required this.invoiceMsats,
    required this.federationFeeMsats,
    required this.gatewayFeeMsats,
  });

  @override
  int get hashCode =>
      invoiceMsats.hashCode ^
      federationFeeMsats.hashCode ^
      gatewayFeeMsats.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReceiveAmount &&
          runtimeType == other.runtimeType &&
          invoiceMsats == other.invoiceMsats &&
          federationFeeMsats == other.federationFeeMsats &&
          gatewayFeeMsats == other.gatewayFeeMsats;
}

/// The wallet-facing grouping a recovering Fedimint module belongs to.
///
/// The dashboard shows one recovery bar per payment type, but a federation can
/// run more than one module behind a single bar (`mint` and `mintv2` both back
/// Ecash), and the module instance ids themselves are not stable: guardians
/// assign them by enumerating the *enabled* modules in alphabetical order of
/// kind, so a v2-only federation numbers them lnv2=0, meta=1, mintv2=2,
/// walletv2=3 while a legacy one numbers them ln=0, mint=1, wallet=2. Resolving
/// the kind here and keying progress on this enum keeps the instance ids on the
/// Rust side, where the client config can be consulted, instead of hardcoding a
/// layout in the UI.
enum RecoveryModule { lightning, ecash, onchain }

class ReissueFees {
  final BigInt totalMsats;
  final BigInt inputMsats;
  final BigInt outputMsats;
  final BigInt dustMsats;

  const ReissueFees({
    required this.totalMsats,
    required this.inputMsats,
    required this.outputMsats,
    required this.dustMsats,
  });

  @override
  int get hashCode =>
      totalMsats.hashCode ^
      inputMsats.hashCode ^
      outputMsats.hashCode ^
      dustMsats.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReissueFees &&
          runtimeType == other.runtimeType &&
          totalMsats == other.totalMsats &&
          inputMsats == other.inputMsats &&
          outputMsats == other.outputMsats &&
          dustMsats == other.dustMsats;
}

enum RelayStatusKind { connecting, connected, failed }

class Transaction {
  final TransactionKind kind;
  final BigInt amount;
  final BigInt timestamp;
  final Uint8List operationId;

  const Transaction({
    required this.kind,
    required this.amount,
    required this.timestamp,
    required this.operationId,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      amount.hashCode ^
      timestamp.hashCode ^
      operationId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Transaction &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          amount == other.amount &&
          timestamp == other.timestamp &&
          operationId == other.operationId;
}

@freezed
sealed class TransactionKind with _$TransactionKind {
  const TransactionKind._();

  const factory TransactionKind.lightningReceive({
    /// On-federation fee (lightning input fee + mint output fees + dust), as
    /// quoted at the invoice amount when the invoice was created.
    required BigInt federationFees,

    /// Gateway off-chain routing fee; always 0 for LNv1.
    required BigInt gatewayFees,

    /// The invoice's face value (what the payer pays). `invoice_amount -
    /// federation_fees - gateway_fees` is what was credited; the
    /// transaction's `amount` is the requested amount shown in the history
    /// list.
    required BigInt invoiceAmount,
    required String gateway,
    required String payeePubkey,
    required String paymentHash,
  }) = TransactionKind_LightningReceive;
  const factory TransactionKind.lightningSend({
    /// On-federation fee: lightning output fee + mint funding/change fees +
    /// dust, quoted at send time via `send_fee_quote`.
    required BigInt federationFees,

    /// Gateway off-chain routing fee.
    required BigInt gatewayFees,
    required String gateway,

    /// The BOLT11 invoice that was paid.
    required String invoice,
    required String paymentHash,
    required String preimage,
    String? lnAddress,
  }) = TransactionKind_LightningSend;
  const factory TransactionKind.lightningRecurring({
    /// The Lightning Address (`username@domain`) registered for this
    /// federation that received the payment, looked up from
    /// `LightningAddressKey` (one address per federation). `None` if no
    /// address is currently registered for the federation.
    String? lnAddress,

    /// On-federation fee actually charged when the incoming contract was
    /// claimed (mint input/output fees), derived from the operation's
    /// input/output difference via `get_operation_fees`. `None` for receives
    /// that predate fee tracking.
    BigInt? federationFees,

    /// Gateway off-chain routing fee. The LNURL invoice is minted by
    /// recurringd and never seen by this client, so for LNv2 the fee is
    /// recovered from the fee-encoded contract expiration
    /// (`fee_from_expiration`). `Some(0)` for LNv1 (no gateway layer);
    /// `None` when unrecoverable (LNv2 contracts created before fee-encoding
    /// existed). The gross invoice the payer paid is `amount +
    /// federation_fees + gateway_fees`.
    BigInt? gatewayFees,
  }) = TransactionKind_LightningRecurring;
  const factory TransactionKind.onchainReceive({
    required String address,
    required String txid,

    /// Federation fee actually charged on the claimed deposit, in msats.
    /// `None` for deposits made before the fee-tracking feature existed.
    BigInt? federationFeeMsats,

    /// Dynamic on-chain claim/sweep fee actually paid when the deposit was
    /// claimed, in msats. This is the real fee (queried at claim time),
    /// not the estimate shown at address-generation time. walletv2 only;
    /// `None` for walletv1 (which has no separate claim fee) and for
    /// deposits predating fee tracking.
    BigInt? onchainClaimFeeMsats,
  }) = TransactionKind_OnchainReceive;
  const factory TransactionKind.onchainSend({
    required String address,
    required String txid,
    double? feeRateSatsPerVb,
    int? txSizeVb,

    /// On-chain Bitcoin miner fee, in sats.
    BigInt? feeSats,
    BigInt? totalSats,

    /// On-federation fee (wallet output fee + mint funding/change fees +
    /// dust), in msats, quoted at send time via `send_fee_quote`.
    BigInt? federationFeeMsats,
  }) = TransactionKind_OnchainSend;
  const factory TransactionKind.ecashReceive({
    required String oobNotes,
    BigInt? inputFees,
    BigInt? outputFees,
    BigInt? dust,
  }) = TransactionKind_EcashReceive;
  const factory TransactionKind.ecashSend({
    required String oobNotes,
    required BigInt fees,
  }) = TransactionKind_EcashSend;
}

class Utxo {
  final String txid;
  final int index;
  final BigInt amount;

  const Utxo({required this.txid, required this.index, required this.amount});

  @override
  int get hashCode => txid.hashCode ^ index.hashCode ^ amount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Utxo &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          index == other.index &&
          amount == other.amount;
}
