// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'app_error.dart';
import 'db.dart';
import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'multimint.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `await_receive_lnv1`, `await_receive_lnv2`, `await_send_lnv1`, `await_send_lnv2`, `backup`, `build_client`, `cache_btc_price`, `cache_federation_meta`, `check_for_update`, `compute_send_fees`, `extract_recipient_pk_from_lnv2_lnurl`, `finish_active_subscriptions`, `from_peg_out_fees`, `get_client_database`, `get_client`, `get_ecash_amount_from_meta`, `get_lnv1_amount_from_meta`, `get_lnv1_receive_tx`, `get_lnv1_send_tx`, `get_lnv2_amount_from_meta`, `get_mintv2_receive_amount`, `get_or_build_temp_client`, `get_recurringd_federations`, `get_url`, `gross_invoice_for_contract`, `init_recovery_progress_cache`, `invoice_routes_back_to_federation`, `is_newer_version`, `list_gateways`, `lnv1_select_gateway`, `lnv1_update_gateway_cache`, `lnv2_gateways`, `lnv2_select_gateway`, `load_clients`, `pay_lnv1`, `pay_lnv2`, `read_meta_msats`, `read_meta_u64`, `receive_lnv1`, `receive_lnv2`, `remove_existing_ln_address`, `remove_recovery_progress_cache`, `run_migrations`, `send_federation_fee`, `sign_challenge`, `solve_gross_for_net`, `spawn_await_ecash_reissue`, `spawn_await_ecash_send`, `spawn_await_mintv2_receive`, `spawn_await_receive`, `spawn_await_recurringd_receive`, `spawn_await_send`, `spawn_await_withdraw`, `spawn_backfill_recipient_pk`, `spawn_cache_task`, `spawn_lnv2_event_listener`, `spawn_recovery_progress`, `spawn_recurring_invoice_listener`, `update_recovery_progress_cache`, `wait_for_recovery`, `wallet_network`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ClientType`, `LNAddressRegisterRequest`, `LNAddressRemoveRequest`, `OnChainWithdrawalMeta`, `WrappedEcash`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `consensus_decode_partial_from_finite_reader`, `consensus_decode_partial_from_finite_reader`, `consensus_decode_partial_from_finite_reader`, `consensus_encode`, `consensus_encode`, `consensus_encode`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`
// These functions have error during generation (see debug logs or enable `stop_on_error: true` for more details): `subscribe_peer_status`

OobNotesWrapper? parseOobNotes({required String notes}) =>
    RustLib.instance.api.crateMultimintParseOobNotes(notes: notes);

/// Returns true if `ecash` is mintv2 `ECash` (rather than walletv1 `OOBNotes`).
/// Used by the UI to gate features that only exist for walletv1, e.g. the
/// claim-status check, which mintv2 has no endpoint for yet.
bool isMintv2Ecash({required String ecash}) =>
    RustLib.instance.api.crateMultimintIsMintv2Ecash(ecash: ecash);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Amount>>
abstract class Amount implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Bolt11Invoice>>
abstract class Bolt11Invoice implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EcashAppResult < OOBNotesWrapper >>>
abstract class EcashAppResultOobNotesWrapper implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EcashAppResult < OperationId >>>
abstract class EcashAppResultOperationId implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EcashAppResult < SpendOOBState >>>
abstract class EcashAppResultSpendOobState implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EcashAppResult < String >>>
abstract class EcashAppResultString implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EcashAppResult < WithdrawFeesResponse >>>
abstract class EcashAppResultWithdrawFeesResponse
    implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EcashAppResult < u64 >>>
abstract class EcashAppResultU64 implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FederationMeta>>
abstract class FederationMeta implements RustOpaqueInterface {
  List<Guardian> get guardians;

  BigInt get lastUpdated;

  String? get lnaddressApi;

  String? get picture;

  String? get recurringdApi;

  FederationSelector get selector;

  String? get welcome;

  set guardians(List<Guardian> guardians);

  set lastUpdated(BigInt lastUpdated);

  set lnaddressApi(String? lnaddressApi);

  set picture(String? picture);

  set recurringdApi(String? recurringdApi);

  set selector(FederationSelector selector);

  set welcome(String? welcome);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FederationSelector>>
abstract class FederationSelector implements RustOpaqueInterface {
  FederationId get federationId;

  String get federationName;

  String? get network;

  set federationId(FederationId federationId);

  set federationName(String federationName);

  set network(String? network);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FinalReceiveOperationState>>
abstract class FinalReceiveOperationState implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Multimint>>
abstract class Multimint implements RustOpaqueInterface {
  Future<void> ackSeedPhrase();

  Future<(String, BigInt?)> allocateDepositAddress({
    required FederationId federationId,
  });

  Future<(ReissueExternalNotesState, BigInt?)> awaitEcashReissue({
    required FederationId federationId,
    required OperationId operationId,
  });

  Future<EcashAppResultSpendOobState> awaitEcashSend({
    required FederationId federationId,
    required OperationId operationId,
  });

  Future<(FinalReceiveOperationState, BigInt)> awaitReceive({
    required FederationId federationId,
    required OperationId operationId,
  });

  Future<LightningSendOutcome> awaitSend({
    required FederationId federationId,
    required OperationId operationId,
  });

  Future<EcashAppResultString> awaitWithdraw({
    required FederationId federationId,
    required OperationId operationId,
  });

  Future<BigInt> balance({required FederationId federationId});

  Future<ReissueFees> calculateEcashReissueFees({
    required FederationId federationId,
    required String ecash,
  });

  /// Quotes a [`Self::send_ecash`] of `amount_msats` without spending
  /// anything, returning both the *actual* amount the send will spend and the
  /// federation fee on top.
  ///
  /// Both mint modules round the requested amount up to a representable
  /// denomination before producing notes (mintv1 to the smallest economical
  /// denomination via `FeeConsensus::round_up`, mintv2 to a multiple of the
  /// smallest client denomination), so the actual amount can exceed what the
  /// user typed. We mirror that rounding here so the review screen shows the
  /// amount that will really be spent, then quote the fee at that amount.
  ///
  /// The fee comes from the same `send_fee_quote` both modules expose: zero
  /// when the wallet already holds exact-change notes (the send just hands
  /// them out), otherwise the cost of the self-reissue the send performs. The
  /// quote is point-in-time over the current note inventory and display-only.
  Future<EcashSendFees> calculateEcashSendFees({
    required FederationId federationId,
    required BigInt amountMsats,
  });

  Future<EcashAppResultWithdrawFeesResponse> calculateWithdrawFees({
    required FederationId federationId,
    required String address,
    required BigInt amountSats,
  });

  Future<bool> checkEcashSpent({
    required FederationId federationId,
    required String ecash,
  });

  Future<LNAddressStatus> checkLnAddressAvailability({
    required String username,
    required String domain,
    required String lnAddressApi,
    required String recurringdApi,
    required FederationId federationId,
  });

  Future<void> clearPinHash();

  Future<List<GatewayPaymentPreview>> computeAllGatewayPreviews({
    required FederationId federationId,
    required Amount amount,
    required Bolt11Invoice bolt11,
  });

  /// Computes the invoice amount and fee breakdown for a receive.
  ///
  /// When `include_fees` is true the fees are added on top of `amount`, so the
  /// sender covers them and exactly `amount` is credited to the receiver. When
  /// it is false the invoice equals `amount` exactly — the sender pays only what
  /// was requested and the receiver absorbs the fees, netting `amount` minus the
  /// fees. In both cases the returned `invoice_msats` is the invoice face value
  /// and the receiver nets `invoice_msats - federation_fee_msats -
  /// gateway_fee_msats`.
  Future<ReceiveAmount> computeReceiveAmountWithFees({
    required FederationId federationId,
    required SafeUrl gatewayUrl,
    required bool isLnv2,
    required Amount amount,
    required bool includeFees,
  });

  Future<bool> containsClient({required FederationId federationId});

  Future<List<(FederationSelector, bool)>> federations();

  Future<List<(String, BigInt?, BigInt?)>> getAddresses({
    required FederationId federationId,
  });

  Future<List<(FiatCurrency, BigInt)>?> getAllBtcPrices();

  Future<List<String>> getAllInviteCodes();

  Future<BitcoinDisplay> getBitcoinDisplay();

  Future<BigInt?> getBtcPrice();

  Future<FederationMeta> getCachedFederationMeta({
    String? invite,
    FederationId? federationId,
  });

  Future<List<FederationId>?> getFederationOrder();

  Future<FiatCurrency> getFiatCurrency();

  Future<String> getInviteCode({
    required FederationId federationId,
    required int peer,
  });

  /// Retreives currently configured Lightning Address
  Future<LightningAddressConfig?> getLnAddressConfig({
    required FederationId federationId,
  });

  Future<EcashAppResultU64> getMaxWithdrawableAmount({
    required FederationId federationId,
    required String address,
  });

  Future<List<String>> getMnemonic();

  Future<List<(BigInt, BigInt)>> getNoteSummary({
    required FederationId federationId,
  });

  Future<PeginFeeQuote> getPeginFeeQuote({required FederationId federationId});

  Future<RecoveryProgress> getRecoveryProgress({
    required FederationId federationId,
    required int moduleId,
  });

  Future<bool> getRequirePinForSpending();

  Future<bool> getShowMsats();

  Future<bool> hasPinCode();

  Future<bool> hasSeedPhraseAck();

  Future<FederationSelector> joinFederation({
    required String invite,
    required bool recover,
  });

  Future<void> leaveFederation({required FederationId federationId});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<Multimint> newInstance({
    required Database db,
    required MultimintCreation creationType,
  }) => RustLib.instance.api.crateMultimintMultimintNew(
    db: db,
    creationType: creationType,
  );

  Future<BigInt> parseEcash({
    required FederationId federationId,
    required OobNotes notes,
  });

  Future<(Bolt11Invoice, OperationId)> receive({
    required FederationId federationId,
    required BigInt amountMsatsWithFees,
    required BigInt amountMsatsWithoutFees,
    required BigInt federationFeeMsats,
    required BigInt gatewayFeeMsats,
    required SafeUrl gateway,
    required bool isLnv2,
  });

  Future<void> recheckAddress({
    required FederationId federationId,
    required BigInt tweakIdx,
  });

  /// Attempt to recover a Lightning Address after wallet recovery.
  /// Uses the deterministic recipient_pk to reverse-lookup on the lnaddr server.
  Future<void> recoverLnAddress({
    required FederationId federationId,
    required String lnAddressApi,
    required String recurringdApi,
  });

  /// Pre-warm guardian connections for every joined federation.
  ///
  /// On Android, sockets to guardians often drop while the app is
  /// backgrounded and don't reconnect on their own. Calling this on app
  /// resume kicks off one connection attempt per peer per federation;
  /// already-live connections are no-ops and failures back off internally.
  Future<void> refreshConnections();

  /// Register LNURL/LN Address
  Future<void> registerLnAddress({
    required FederationId federationId,
    required String recurringdApi,
    required String lnAddressApi,
    required String username,
    required String domain,
  });

  Future<EcashAppResultOperationId> reissueEcash({
    required FederationId federationId,
    required String ecash,
    required ReissueFees fees,
  });

  Future<void> rejoinFromBackupInvites({
    required List<String> backupInviteCodes,
  });

  Future<SendGatewaySelection> selectSendGateway({
    required FederationId federationId,
    required Amount amount,
    required Bolt11Invoice bolt11,
  });

  Future<EcashAppResultOperationId> send({
    required FederationId federationId,
    required String invoice,
    required SafeUrl gateway,
    required bool isLnv2,
    required BigInt amountWithFees,
    required BigInt federationFeeMsats,
    required BigInt gatewayFeeMsats,
    String? lnAddress,
  });

  Future<EcashAppResultOobNotesWrapper> sendEcash({
    required FederationId federationId,
    required BigInt amountMsats,
    required BigInt feeMsats,
  });

  Future<void> setBitcoinDisplay({required BitcoinDisplay bitcoinDisplay});

  Future<void> setFederationOrder({required List<FederationId> order});

  Future<void> setFiatCurrency({required FiatCurrency fiatCurrency});

  Future<void> setPinHash({required String pin});

  Future<void> setRequirePinForSpending({required bool require});

  Future<void> setShowMsats({required bool showMsats});

  Future<List<Transaction>> transactions({
    required FederationId federationId,
    BigInt? timestamp,
    Uint8List? operationId,
    required List<String> modules,
  });

  Future<bool> verifyPin({required String pin});

  Future<List<Utxo>> walletSummary({
    String? invite,
    FederationId? federationId,
  });

  Future<EcashAppResultOperationId> withdrawToAddress({
    required FederationId federationId,
    required String address,
    required BigInt amountSats,
    required WithdrawFees fees,
    required BigInt federationFeeMsats,
  });
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<OOBNotes>>
abstract class OobNotes implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<OOBNotesWrapper>>
abstract class OobNotesWrapper implements RustOpaqueInterface {
  BigInt amountMsats();

  @override
  String toString();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<OperationId>>
abstract class OperationId implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RecoveryProgress>>
abstract class RecoveryProgress implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ReissueExternalNotesState>>
abstract class ReissueExternalNotesState implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WithdrawFees>>
abstract class WithdrawFees implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WithdrawFeesResponse>>
abstract class WithdrawFeesResponse implements RustOpaqueInterface {
  BigInt get federationFeeMsats;

  BigInt get feeAmount;

  double get feeRateSatsPerVb;

  WithdrawFees get fees;

  int get txSizeVbytes;

  set federationFeeMsats(BigInt federationFeeMsats);

  set feeAmount(BigInt feeAmount);

  set feeRateSatsPerVb(double feeRateSatsPerVb);

  set fees(WithdrawFees fees);

  set txSizeVbytes(int txSizeVbytes);
}

class AwaitingConfsEvent {
  final BigInt amount;
  final String outpoint;
  final BigInt blockHeight;
  final BigInt needed;

  const AwaitingConfsEvent({
    required this.amount,
    required this.outpoint,
    required this.blockHeight,
    required this.needed,
  });

  @override
  int get hashCode =>
      amount.hashCode ^
      outpoint.hashCode ^
      blockHeight.hashCode ^
      needed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AwaitingConfsEvent &&
          runtimeType == other.runtimeType &&
          amount == other.amount &&
          outpoint == other.outpoint &&
          blockHeight == other.blockHeight &&
          needed == other.needed;
}

class ClaimedEvent {
  final BigInt amount;
  final String outpoint;

  const ClaimedEvent({required this.amount, required this.outpoint});

  @override
  int get hashCode => amount.hashCode ^ outpoint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClaimedEvent &&
          runtimeType == other.runtimeType &&
          amount == other.amount &&
          outpoint == other.outpoint;
}

class ConfirmedEvent {
  final BigInt amount;
  final String outpoint;

  const ConfirmedEvent({required this.amount, required this.outpoint});

  @override
  int get hashCode => amount.hashCode ^ outpoint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConfirmedEvent &&
          runtimeType == other.runtimeType &&
          amount == other.amount &&
          outpoint == other.outpoint;
}

@freezed
sealed class ContactSyncEventKind with _$ContactSyncEventKind {
  const ContactSyncEventKind._();

  const factory ContactSyncEventKind.started() = ContactSyncEventKind_Started;
  const factory ContactSyncEventKind.progress({required BigInt synced}) =
      ContactSyncEventKind_Progress;
  const factory ContactSyncEventKind.completed({
    required BigInt added,
    required BigInt updated,
    required BigInt removed,
  }) = ContactSyncEventKind_Completed;
  const factory ContactSyncEventKind.error(String field0) =
      ContactSyncEventKind_Error;
}

@freezed
sealed class DepositEventKind with _$DepositEventKind {
  const DepositEventKind._();

  const factory DepositEventKind.mempool(MempoolEvent field0) =
      DepositEventKind_Mempool;
  const factory DepositEventKind.awaitingConfs(AwaitingConfsEvent field0) =
      DepositEventKind_AwaitingConfs;
  const factory DepositEventKind.confirmed(ConfirmedEvent field0) =
      DepositEventKind_Confirmed;
  const factory DepositEventKind.claimed(ClaimedEvent field0) =
      DepositEventKind_Claimed;
}

/// Quote for an ecash send. `amount_msats` is the *actual* amount the send will
/// spend on the ecash: the requested amount rounded up to a representable
/// denomination, which both mint modules do before producing notes, so it can
/// exceed what the user typed. `fee_msats` is the federation fee charged on top.
/// The total debited from the wallet is `amount_msats + fee_msats`.
class EcashSendFees {
  final BigInt amountMsats;
  final BigInt feeMsats;

  const EcashSendFees({required this.amountMsats, required this.feeMsats});

  @override
  int get hashCode => amountMsats.hashCode ^ feeMsats.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EcashSendFees &&
          runtimeType == other.runtimeType &&
          amountMsats == other.amountMsats &&
          feeMsats == other.feeMsats;
}

class FedimintGateway {
  final String endpoint;
  final BigInt baseRoutingFee;
  final BigInt ppmRoutingFee;
  final BigInt baseTransactionFee;
  final BigInt ppmTransactionFee;
  final String? lightningAlias;
  final String? lightningNode;
  final bool isLnv2;
  final bool isVettted;

  /// LNv1 only: short_channel_id used in route hints to identify the federation.
  /// Used to detect "loopback" invoices issued by the same federation, which
  /// incur zero gateway routing fees.
  final BigInt? federationIndex;

  /// LNv2 only: gateway's minimum send fee, applied on loopback payments
  /// (where the invoice's payee is the gateway's own Lightning node).
  final BigInt? minBaseRoutingFee;
  final BigInt? minPpmRoutingFee;

  const FedimintGateway({
    required this.endpoint,
    required this.baseRoutingFee,
    required this.ppmRoutingFee,
    required this.baseTransactionFee,
    required this.ppmTransactionFee,
    this.lightningAlias,
    this.lightningNode,
    required this.isLnv2,
    required this.isVettted,
    this.federationIndex,
    this.minBaseRoutingFee,
    this.minPpmRoutingFee,
  });

  @override
  int get hashCode =>
      endpoint.hashCode ^
      baseRoutingFee.hashCode ^
      ppmRoutingFee.hashCode ^
      baseTransactionFee.hashCode ^
      ppmTransactionFee.hashCode ^
      lightningAlias.hashCode ^
      lightningNode.hashCode ^
      isLnv2.hashCode ^
      isVettted.hashCode ^
      federationIndex.hashCode ^
      minBaseRoutingFee.hashCode ^
      minPpmRoutingFee.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FedimintGateway &&
          runtimeType == other.runtimeType &&
          endpoint == other.endpoint &&
          baseRoutingFee == other.baseRoutingFee &&
          ppmRoutingFee == other.ppmRoutingFee &&
          baseTransactionFee == other.baseTransactionFee &&
          ppmTransactionFee == other.ppmTransactionFee &&
          lightningAlias == other.lightningAlias &&
          lightningNode == other.lightningNode &&
          isLnv2 == other.isLnv2 &&
          isVettted == other.isVettted &&
          federationIndex == other.federationIndex &&
          minBaseRoutingFee == other.minBaseRoutingFee &&
          minPpmRoutingFee == other.minPpmRoutingFee;
}

class GatewayPaymentPreview {
  final FedimintGateway gateway;
  final BigInt amountWithFees;

  /// Gateway off-chain routing fee (baked into the outgoing contract).
  final BigInt gatewayFee;

  /// On-federation fee: lightning output fee + mint funding/change fees +
  /// dust, quoted via the lightning module's `send_fee_quote`.
  final BigInt federationFee;

  const GatewayPaymentPreview({
    required this.gateway,
    required this.amountWithFees,
    required this.gatewayFee,
    required this.federationFee,
  });

  @override
  int get hashCode =>
      gateway.hashCode ^
      amountWithFees.hashCode ^
      gatewayFee.hashCode ^
      federationFee.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GatewayPaymentPreview &&
          runtimeType == other.runtimeType &&
          gateway == other.gateway &&
          amountWithFees == other.amountWithFees &&
          gatewayFee == other.gatewayFee &&
          federationFee == other.federationFee;
}

class Guardian {
  final int peerId;
  final String name;
  final String? version;

  const Guardian({required this.peerId, required this.name, this.version});

  @override
  int get hashCode => peerId.hashCode ^ name.hashCode ^ version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Guardian &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          name == other.name &&
          version == other.version;
}

class InvoicePaidEvent {
  final BigInt amountMsats;

  const InvoicePaidEvent({required this.amountMsats});

  @override
  int get hashCode => amountMsats.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InvoicePaidEvent &&
          runtimeType == other.runtimeType &&
          amountMsats == other.amountMsats;
}

@freezed
sealed class LightningEventKind with _$LightningEventKind {
  const LightningEventKind._();

  const factory LightningEventKind.invoicePaid(InvoicePaidEvent field0) =
      LightningEventKind_InvoicePaid;
  const factory LightningEventKind.paymentSent() =
      LightningEventKind_PaymentSent;
}

@freezed
sealed class LightningSendOutcome with _$LightningSendOutcome {
  const LightningSendOutcome._();

  const factory LightningSendOutcome.success(String field0) =
      LightningSendOutcome_Success;

  /// Carries the typed reason for the failure so the Dart layer can render
  /// a localized message on the Failure screen.
  const factory LightningSendOutcome.failure(EcashAppError field0) =
      LightningSendOutcome_Failure;
}

@freezed
sealed class LNAddressStatus with _$LNAddressStatus {
  const LNAddressStatus._();

  const factory LNAddressStatus.registered({required String lnurl}) =
      LNAddressStatus_Registered;
  const factory LNAddressStatus.available() = LNAddressStatus_Available;
  const factory LNAddressStatus.currentConfig() = LNAddressStatus_CurrentConfig;
  const factory LNAddressStatus.unsupportedFederation() =
      LNAddressStatus_UnsupportedFederation;
  const factory LNAddressStatus.invalid() = LNAddressStatus_Invalid;
}

enum LogLevel { trace, debug, info, warn, error }

class MempoolEvent {
  final BigInt amount;
  final String outpoint;

  const MempoolEvent({required this.amount, required this.outpoint});

  @override
  int get hashCode => amount.hashCode ^ outpoint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MempoolEvent &&
          runtimeType == other.runtimeType &&
          amount == other.amount &&
          outpoint == other.outpoint;
}

@freezed
sealed class MultimintCreation with _$MultimintCreation {
  const MultimintCreation._();

  const factory MultimintCreation.new_() = MultimintCreation_New;
  const factory MultimintCreation.loadExisting() =
      MultimintCreation_LoadExisting;
  const factory MultimintCreation.newFromMnemonic({
    required List<String> words,
  }) = MultimintCreation_NewFromMnemonic;
}

@freezed
sealed class MultimintEvent with _$MultimintEvent {
  const MultimintEvent._();

  const factory MultimintEvent.deposit(
    (FederationId, DepositEventKind) field0,
  ) = MultimintEvent_Deposit;
  const factory MultimintEvent.lightning(
    (FederationId, LightningEventKind) field0,
  ) = MultimintEvent_Lightning;
  const factory MultimintEvent.log(LogLevel field0, String field1) =
      MultimintEvent_Log;
  const factory MultimintEvent.recoveryDone(String field0) =
      MultimintEvent_RecoveryDone;
  const factory MultimintEvent.recoveryProgress(
    String field0,
    int field1,
    int field2,
    int field3,
  ) = MultimintEvent_RecoveryProgress;
  const factory MultimintEvent.ecash((FederationId, BigInt) field0) =
      MultimintEvent_Ecash;
  const factory MultimintEvent.nostrRecovery(
    String field0,
    int field1, [
    FederationSelector? field2,
  ]) = MultimintEvent_NostrRecovery;
  const factory MultimintEvent.nostrRelayStatus(
    String field0,
    RelayStatusKind field1,
  ) = MultimintEvent_NostrRelayStatus;
  const factory MultimintEvent.nostrRecoveryPhase(NostrRecoveryPhase field0) =
      MultimintEvent_NostrRecoveryPhase;
  const factory MultimintEvent.contactSync(ContactSyncEventKind field0) =
      MultimintEvent_ContactSync;
  const factory MultimintEvent.updateAvailable(String field0) =
      MultimintEvent_UpdateAvailable;

  /// Structured payment-flow error. The Dart layer auto-surfaces these as
  /// localized error toasts (see `lib/app.dart` and `lib/error_helper.dart`).
  const factory MultimintEvent.paymentError(
    (FederationId, EcashAppError) field0,
  ) = MultimintEvent_PaymentError;
}

@freezed
sealed class NostrRecoveryPhase with _$NostrRecoveryPhase {
  const NostrRecoveryPhase._();

  const factory NostrRecoveryPhase.connectingToRelays() =
      NostrRecoveryPhase_ConnectingToRelays;
  const factory NostrRecoveryPhase.fetchingBackup() =
      NostrRecoveryPhase_FetchingBackup;
  const factory NostrRecoveryPhase.decryptingInvites() =
      NostrRecoveryPhase_DecryptingInvites;
  const factory NostrRecoveryPhase.rejoiningFederations(int field0) =
      NostrRecoveryPhase_RejoiningFederations;
}

class PaymentPreviewWithGateways {
  final BigInt amountMsats;
  final String paymentHash;
  final String network;
  final String invoice;
  final List<GatewayPaymentPreview> gatewayPreviews;
  final BigInt selectedIndex;

  const PaymentPreviewWithGateways({
    required this.amountMsats,
    required this.paymentHash,
    required this.network,
    required this.invoice,
    required this.gatewayPreviews,
    required this.selectedIndex,
  });

  @override
  int get hashCode =>
      amountMsats.hashCode ^
      paymentHash.hashCode ^
      network.hashCode ^
      invoice.hashCode ^
      gatewayPreviews.hashCode ^
      selectedIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PaymentPreviewWithGateways &&
          runtimeType == other.runtimeType &&
          amountMsats == other.amountMsats &&
          paymentHash == other.paymentHash &&
          network == other.network &&
          invoice == other.invoice &&
          gatewayPreviews == other.gatewayPreviews &&
          selectedIndex == other.selectedIndex;
}

enum PeerConnectivity { direct, relay, mixed, tor, unknown }

class PeerStatus {
  final int peerId;
  final String name;
  final bool online;
  final PeerConnectivity connectivity;
  final String url;

  const PeerStatus({
    required this.peerId,
    required this.name,
    required this.online,
    required this.connectivity,
    required this.url,
  });

  @override
  int get hashCode =>
      peerId.hashCode ^
      name.hashCode ^
      online.hashCode ^
      connectivity.hashCode ^
      url.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeerStatus &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          name == other.name &&
          online == other.online &&
          connectivity == other.connectivity &&
          url == other.url;
}

/// Fee parameters for an on-chain deposit (peg-in). We can't quote an exact
/// charge up front because the deposit amount is unknown, and for walletv2 the
/// federation fee scales with the amount, so we surface the parameters instead.
class PeginFeeQuote {
  /// Constant federation fee charged on the deposit, in msats.
  /// walletv1: `peg_in_abs`; walletv2: `fee_consensus.base`.
  final BigInt baseFeeMsats;

  /// Relative federation fee in parts-per-million (walletv2 only; 0 for walletv1).
  final BigInt partsPerMillion;

  /// Dynamic on-chain claim/sweep fee in sats (walletv2 only; `None` for
  /// walletv1 or when no consensus feerate is currently available).
  final BigInt? onchainClaimFeeSats;

  const PeginFeeQuote({
    required this.baseFeeMsats,
    required this.partsPerMillion,
    this.onchainClaimFeeSats,
  });

  @override
  int get hashCode =>
      baseFeeMsats.hashCode ^
      partsPerMillion.hashCode ^
      onchainClaimFeeSats.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeginFeeQuote &&
          runtimeType == other.runtimeType &&
          baseFeeMsats == other.baseFeeMsats &&
          partsPerMillion == other.partsPerMillion &&
          onchainClaimFeeSats == other.onchainClaimFeeSats;
}

/// Result of pricing a Lightning receive. `invoice_msats` is the invoice's face
/// value (what the payer pays). The fee is broken out into its two sources:
/// `federation_fee_msats` (on-federation: lightning input fee plus mint output
/// fees plus dust) and `gateway_fee_msats` (the gateway's off-chain routing fee,
/// always 0 for LNv1). The receiver is credited
/// `invoice_msats - federation_fee_msats - gateway_fee_msats`. Both are quoted at
/// `invoice_msats`, not the requested amount, so they match what is really
/// deducted.
class ReceiveAmount {
  final BigInt invoiceMsats;
  final BigInt federationFeeMsats;
  final BigInt gatewayFeeMsats;

  const ReceiveAmount({
    required this.invoiceMsats,
    required this.federationFeeMsats,
    required this.gatewayFeeMsats,
  });

  @override
  int get hashCode =>
      invoiceMsats.hashCode ^
      federationFeeMsats.hashCode ^
      gatewayFeeMsats.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReceiveAmount &&
          runtimeType == other.runtimeType &&
          invoiceMsats == other.invoiceMsats &&
          federationFeeMsats == other.federationFeeMsats &&
          gatewayFeeMsats == other.gatewayFeeMsats;
}

class ReissueFees {
  final BigInt totalMsats;
  final BigInt inputMsats;
  final BigInt outputMsats;
  final BigInt dustMsats;

  const ReissueFees({
    required this.totalMsats,
    required this.inputMsats,
    required this.outputMsats,
    required this.dustMsats,
  });

  @override
  int get hashCode =>
      totalMsats.hashCode ^
      inputMsats.hashCode ^
      outputMsats.hashCode ^
      dustMsats.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReissueFees &&
          runtimeType == other.runtimeType &&
          totalMsats == other.totalMsats &&
          inputMsats == other.inputMsats &&
          outputMsats == other.outputMsats &&
          dustMsats == other.dustMsats;
}

enum RelayStatusKind { connecting, connected, failed }

/// Gateway chosen for a Lightning send (used by the LN-address path, which has
/// no on-screen gateway picker), with the same fee breakdown as a preview.
class SendGatewaySelection {
  final String gatewayUrl;
  final BigInt amountWithFees;
  final BigInt gatewayFee;
  final BigInt federationFee;
  final bool isLnv2;

  const SendGatewaySelection({
    required this.gatewayUrl,
    required this.amountWithFees,
    required this.gatewayFee,
    required this.federationFee,
    required this.isLnv2,
  });

  @override
  int get hashCode =>
      gatewayUrl.hashCode ^
      amountWithFees.hashCode ^
      gatewayFee.hashCode ^
      federationFee.hashCode ^
      isLnv2.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendGatewaySelection &&
          runtimeType == other.runtimeType &&
          gatewayUrl == other.gatewayUrl &&
          amountWithFees == other.amountWithFees &&
          gatewayFee == other.gatewayFee &&
          federationFee == other.federationFee &&
          isLnv2 == other.isLnv2;
}

class Transaction {
  final TransactionKind kind;
  final BigInt amount;
  final BigInt timestamp;
  final Uint8List operationId;

  const Transaction({
    required this.kind,
    required this.amount,
    required this.timestamp,
    required this.operationId,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      amount.hashCode ^
      timestamp.hashCode ^
      operationId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Transaction &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          amount == other.amount &&
          timestamp == other.timestamp &&
          operationId == other.operationId;
}

@freezed
sealed class TransactionKind with _$TransactionKind {
  const TransactionKind._();

  const factory TransactionKind.lightningReceive({
    /// On-federation fee (lightning input fee + mint output fees + dust), as
    /// quoted at the invoice amount when the invoice was created.
    required BigInt federationFees,

    /// Gateway off-chain routing fee; always 0 for LNv1.
    required BigInt gatewayFees,

    /// The invoice's face value (what the payer pays). `invoice_amount -
    /// federation_fees - gateway_fees` is what was credited; the
    /// transaction's `amount` is the requested amount shown in the history
    /// list.
    required BigInt invoiceAmount,
    required String gateway,
    required String payeePubkey,
    required String paymentHash,
  }) = TransactionKind_LightningReceive;
  const factory TransactionKind.lightningSend({
    /// On-federation fee: lightning output fee + mint funding/change fees +
    /// dust, quoted at send time via `send_fee_quote`.
    required BigInt federationFees,

    /// Gateway off-chain routing fee.
    required BigInt gatewayFees,
    required String gateway,
    required String paymentHash,
    required String preimage,
    String? lnAddress,
  }) = TransactionKind_LightningSend;
  const factory TransactionKind.lightningRecurring() =
      TransactionKind_LightningRecurring;
  const factory TransactionKind.onchainReceive({
    required String address,
    required String txid,

    /// Federation fee actually charged on the claimed deposit, in msats.
    /// `None` for deposits made before the fee-tracking feature existed.
    BigInt? federationFeeMsats,
  }) = TransactionKind_OnchainReceive;
  const factory TransactionKind.onchainSend({
    required String address,
    required String txid,
    double? feeRateSatsPerVb,
    int? txSizeVb,

    /// On-chain Bitcoin miner fee, in sats.
    BigInt? feeSats,
    BigInt? totalSats,

    /// On-federation fee (wallet output fee + mint funding/change fees +
    /// dust), in msats, quoted at send time via `send_fee_quote`.
    BigInt? federationFeeMsats,
  }) = TransactionKind_OnchainSend;
  const factory TransactionKind.ecashReceive({
    required String oobNotes,
    BigInt? inputFees,
    BigInt? outputFees,
    BigInt? dust,
  }) = TransactionKind_EcashReceive;
  const factory TransactionKind.ecashSend({
    required String oobNotes,
    required BigInt fees,
  }) = TransactionKind_EcashSend;
}

class Utxo {
  final String txid;
  final int index;
  final BigInt amount;

  const Utxo({required this.txid, required this.index, required this.amount});

  @override
  int get hashCode => txid.hashCode ^ index.hashCode ^ amount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Utxo &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          index == other.index &&
          amount == other.amount;
}
