// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'app_error.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decrypt`, `derive_key`, `encrypt_ecash`, `encrypt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TapRecipient>>
abstract class TapRecipient implements RustOpaqueInterface {
  /// Decrypt a blob produced by [`encrypt_ecash`], returning the original
  /// ecash string ready to pass to `reissue_ecash`.
  String decrypt({required List<int> blob});

  factory TapRecipient() =>
      RustLib.instance.api.crateTapTransferTapRecipientNew();

  /// The 33-byte compressed public key to hand to the sender over NFC.
  Uint8List publicKey();
}
